@if($abilities['canCreateCycle'])
<details class="people-ops-panel" id="create-performance-cycle" @if($errors->any()) open @endif>
    <summary class="people-ops-panel-head"><div><h2>Create performance cycle</h2><p>Configure a persisted review period using the existing scoring authority.</p></div></summary>
    <div class="people-ops-panel-body"><form method="POST" action="{{ route('hr.performance-cycles.store') }}" class="people-form-grid">@csrf
        <label class="people-field"><span>Company</span><select class="people-control" name="company_id" required>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((string)old('company_id', auth()->user()->company_id)===(string)$company->id)>{{ $company->name }}</option>@endforeach</select></label>
        <label class="people-field"><span>Cycle name</span><input class="people-control" name="name" maxlength="160" value="{{ old('name') }}" required></label>
        <label class="people-field"><span>Frequency</span><select class="people-control" name="frequency" required>@foreach(['monthly'=>'Monthly','quarterly'=>'Quarterly','annual'=>'Annual'] as $value=>$label)<option value="{{ $value }}" @selected(old('frequency')===$value)>{{ $label }}</option>@endforeach</select></label>
        <label class="people-field"><span>Status</span><select class="people-control" name="status" required>@foreach(['draft'=>'Draft','active'=>'Active'] as $value=>$label)<option value="{{ $value }}" @selected(old('status','draft')===$value)>{{ $label }}</option>@endforeach</select></label>
        <label class="people-field"><span>Starts on</span><input class="people-control" type="date" name="starts_on" value="{{ old('starts_on') }}" required></label>
        <label class="people-field"><span>Ends on</span><input class="people-control" type="date" name="ends_on" value="{{ old('ends_on') }}" required></label>
        <label class="people-field"><span>Review due</span><input class="people-control" type="date" name="review_due_on" value="{{ old('review_due_on') }}"></label>
        <label class="people-field"><span>Department</span><select class="people-control" name="department"><option value="">All departments</option>@foreach($departments as $department)<option value="{{ $department }}" @selected(old('department')===$department)>{{ $department }}</option>@endforeach</select></label>
        <label class="people-field"><span>Project</span><select class="people-control" name="project_id"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((string)old('project_id')===(string)$project->id)>{{ $project->code }} - {{ $project->name }}</option>@endforeach</select></label>
        <label class="people-field"><span>Rating minimum</span><input class="people-control" type="number" name="rating_scale_min" min="1" max="9" step="1" value="{{ old('rating_scale_min',1) }}" required></label>
        <label class="people-field"><span>Rating maximum</span><input class="people-control" type="number" name="rating_scale_max" min="2" max="10" step="1" value="{{ old('rating_scale_max',5) }}" required></label>
        <label class="people-field"><span>Passing score</span><input class="people-control" type="number" name="passing_score" min="1" max="10" step="0.01" value="{{ old('passing_score',3) }}" required></label>
        <button class="people-button is-primary" type="submit">Create cycle</button>
    </form></div>
</details>
@endif

<section class="people-ops-panel has-mobile-cards" aria-labelledby="performance-cycles-title">
    <header class="people-ops-panel-head"><div><h2 id="performance-cycles-title">Performance cycles</h2><p>{{ $cycles->total() }} authorized cycle{{ $cycles->total() === 1 ? '' : 's' }}.</p></div></header>
    <div class="people-ops-panel-body"><form method="GET" action="{{ route('hr.performance-cycles.index') }}" class="people-ops-filterbar"><label class="people-field"><span>Status</span><select class="people-control" name="status"><option value="">All statuses</option>@foreach(['draft'=>'Draft','active'=>'Active','closed'=>'Closed','archived'=>'Archived'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></label><label class="people-field"><span>Frequency</span><select class="people-control" name="frequency"><option value="">All frequencies</option>@foreach(['monthly'=>'Monthly','quarterly'=>'Quarterly','annual'=>'Annual'] as $value=>$label)<option value="{{ $value }}" @selected(request('frequency')===$value)>{{ $label }}</option>@endforeach</select></label><label class="people-field"><span>Department</span><select class="people-control" name="department"><option value="">All departments</option>@foreach($departments as $department)<option value="{{ $department }}" @selected(request('department')===$department)>{{ $department }}</option>@endforeach</select></label><button class="people-button is-primary">Apply filters</button><a class="people-button" href="{{ route('hr.performance-cycles.index') }}">Clear</a></form></div>
    <div class="people-ops-table-wrap"><table class="people-ops-table"><caption>Performance cycles</caption><thead><tr><th scope="col">Cycle</th><th scope="col">Period</th><th scope="col">Population</th><th scope="col">Scale</th><th scope="col">Status</th><th scope="col" class="is-number">Reviews</th></tr></thead><tbody>@forelse($cycles as $cycle)<tr><td><strong>{{ $cycle->code }}</strong><small>{{ $cycle->name }} / {{ ucfirst($cycle->frequency) }}</small></td><td>{{ $cycle->period }}<small>Due {{ $cycle->reviewDue }}</small></td><td>{{ $cycle->department }}<small>{{ $cycle->project }}</small></td><td>{{ $cycle->scale }}<small>Pass {{ $cycle->passingScore }}</small></td><td><span class="people-status is-{{ $cycle->status === 'active' ? 'success' : ($cycle->status === 'draft' ? 'warning' : 'muted') }}">{{ $cycle->statusLabel }}</span></td><td class="is-number">{{ $cycle->reviewCount }}</td></tr>@empty<tr><td colspan="6"><div class="people-ops-empty"><strong>No performance cycles found</strong><span>Clear the filters or create an authorized cycle.</span></div></td></tr>@endforelse</tbody></table></div>
    <div class="people-ops-mobile-list">@forelse($cycles as $cycle)<article class="people-ops-mobile-card"><header class="people-ops-mobile-card-head"><div><strong>{{ $cycle->name }}</strong><small>{{ $cycle->code }}</small></div><span class="people-status is-info">{{ $cycle->statusLabel }}</span></header><dl class="people-ops-mobile-facts"><div><dt>Period</dt><dd>{{ $cycle->period }}</dd></div><div><dt>Department</dt><dd>{{ $cycle->department }}</dd></div><div><dt>Scale</dt><dd>{{ $cycle->scale }}</dd></div><div><dt>Reviews</dt><dd>{{ $cycle->reviewCount }}</dd></div></dl></article>@empty<div class="people-ops-empty"><strong>No performance cycles found</strong></div>@endforelse</div>
    {{ $cycles->withQueryString()->links() }}
</section>
