<?php
namespace App\Domain\Maintenance\Services;
use App\Models\Booking; use App\Models\CommonAreaHandoverItem; use App\Models\Customer; use App\Models\MaintenanceDue; use App\Models\Project; use App\Models\SocietyFormation; use App\Models\User; use App\Services\Security\CompanyScopeService; use App\Support\PaginationPolicy; use Illuminate\Pagination\LengthAwarePaginator; use Illuminate\Support\Collection;
final class MaintenanceRegister
{
    public function __construct(private readonly CompanyScopeService $scope,private readonly PaginationPolicy $pagination) {}
    public function isBuyer(User $actor): bool { return $actor->role?->slug==='buyer'&&$actor->hasPermission('buyer.view'); }
    public function societies(User $actor,array $filters): LengthAwarePaginator { return $this->scope->apply(SocietyFormation::query()->with(['project','createdBy','updatedBy']),$actor)->when($filters['project_id']??null,fn($q,int $id)=>$q->where('project_id',$id))->when($filters['status']??null,fn($q,string $s)=>$q->where('status',$s))->orderByRaw("case when status in ('formed', 'handed_over') then 1 else 0 end")->orderByDesc('updated_at')->paginate($this->pagination->workspacePerPage($filters['per_page']??null))->withQueryString(); }
    public function items(User $actor,array $filters): LengthAwarePaginator { return $this->scope->apply(CommonAreaHandoverItem::query()->with(['project','societyFormation','responsibleUser','signedOffBy']),$actor)->when($filters['project_id']??null,fn($q,int $id)=>$q->where('project_id',$id))->when($filters['society_formation_id']??null,fn($q,int $id)=>$q->where('society_formation_id',$id))->when($filters['status']??null,fn($q,string $s)=>$q->where('status',$s))->orderByRaw("case when status = 'complete' then 1 else 0 end")->orderBy('facility_name')->paginate($this->pagination->workspacePerPage($filters['per_page']??null))->withQueryString(); }
    public function dues(User $actor,array $filters): LengthAwarePaginator { $q=MaintenanceDue::query()->with(['project','booking','customer','unit','raisedBy','paidBy']); if($this->isBuyer($actor))$q->whereHas('customer',fn($c)=>$c->where('portal_user_id',$actor->id)); else $this->scope->apply($q,$actor); return $q->when($filters['project_id']??null,fn($q,int $id)=>$q->where('project_id',$id))->when($filters['customer_id']??null,fn($q,int $id)=>$q->where('customer_id',$id))->when($filters['status']??null,fn($q,string $s)=>$q->where('status',$s))->orderByRaw("case when status in ('due', 'overdue') then 0 else 1 end")->orderBy('due_on')->paginate($this->pagination->workspacePerPage($filters['per_page']??null))->withQueryString(); }
    public function projects(User $actor): Collection { return $this->scope->apply(Project::query()->select(['id','company_id','code','name','status'])->where('status','active'),$actor)->orderBy('code')->get(); }
    public function societyOptions(User $actor): Collection { return $this->scope->apply(SocietyFormation::query()->select(['id','company_id','project_id','formation_number','society_name','status']),$actor)->orderBy('formation_number')->get(); }
    public function bookings(User $actor): Collection { return $this->scope->apply(Booking::query()->with(['project:id,code,name','unit:id,unit_code','customer:id,code,name'])->whereIn('status',['confirmed','agreement_pending','registered'])->whereNotNull('project_unit_id'),$actor)->orderByDesc('booked_on')->orderBy('booking_code')->limit(150)->get(); }
    public function customers(User $actor): Collection { $ids=$this->scope->apply(Booking::query()->select('customer_id')->whereNotNull('customer_id'),$actor); return Customer::query()->whereIn('id',$ids)->orderBy('name')->get(['id','code','name']); }
}
