<div class="tm-body pad">
@if ($scope === 'activity')
    @php
        $activityFilter = $filters['activity_filter'] ?? 'all';
    @endphp
    <div class="tm-dashboard-heading"><div><h1>Activity Center</h1><p>Every action across tasks available to your role.</p></div><nav class="tm-activity-filters" aria-label="Activity filters">@foreach(['all'=>'All','comments'=>'Comments','status'=>'Status','transfers'=>'Transfers','approvals'=>'Approvals','attachments'=>'Attachments','time'=>'Time'] as $key=>$label)<a class="{{ $activityFilter===$key ? 'on' : '' }}" href="{{ route('collaboration.tasks.index',$taskQuery(['scope'=>'activity','activity_filter'=>$key])) }}">{{ $label }}</a>@endforeach</nav></div>
    <article class="blade-dashboard-card tm-insight-card">
        @forelse($taskActivity as $item)
            <a class="tm-act-row tm-act-{{ $item['tone'] }}" href="{{ route('collaboration.tasks.index',$taskQuery(['task_id'=>$item['task_id']])) }}">
                <span class="tm-act-ic"><i class="fa-solid {{ $item['icon'] }}"></i></span>
                <span><b>{{ $item['task_number'] }}</b> {{ $item['label'] }}<small>{{ $item['actor'] ? $item['actor'].' · ' : '' }}{{ $item['task_title'] }}</small></span>
                <time datetime="{{ $item['at'] }}" title="{{ $item['absolute_time'] }}">{{ $item['relative_time'] }}</time>
            </a>
        @empty
            <div class="tm-empty-panel"><span class="tm-empty-ic"><i class="fa-solid fa-wave-square"></i></span><span><b>No {{ $activityFilter === 'all' ? '' : $activityFilter.' ' }}activity</b><small>Task updates matching this filter will appear here.</small></span></div>
        @endforelse
    </article>
@elseif ($scope === 'reports')
    <div class="tm-dashboard-heading"><div><h1>Reports</h1><p>Reports calculated from all tasks available to your role.</p></div><div class="tm-action-row"><a class="tm-tbtn" href="{{ route('collaboration.tasks.export',$taskQuery(['format'=>'csv'])) }}"><i class="fa-solid fa-download"></i> Export CSV</a><a class="tm-tbtn" href="{{ route('collaboration.tasks.export',$taskQuery(['format'=>'pdf'])) }}"><i class="fa-solid fa-file-pdf"></i> Export PDF</a></div></div>
    <section class="tm-dash-grid">@foreach([['Task Completion',$taskSummary['completed'].' completed of '.$taskSummary['total'],'fa-circle-check'],['Task Aging',$taskSummary['overdue'].' overdue task(s)','fa-clock'],['Approval Queue',$taskSummary['awaiting_approval'].' awaiting approval','fa-shield-halved'],['Critical Work',$taskSummary['critical'].' critical task(s)','fa-fire']] as [$title,$sub,$icon])<article class="tm-tpl-card"><span class="tm-tpl-ic"><i class="fa-solid {{ $icon }}"></i></span><h3>{{ $title }}</h3><p>{{ $sub }}</p></article>@endforeach</section>
@elseif ($scope === 'analytics')
    <div class="tm-dashboard-heading"><div><h1>Analytics</h1><p>Performance calculated from status, due dates and workflow records.</p></div></div>
    <section class="tm-dash-grid">@foreach([['Completion rate',$taskSummary['completion_rate'].'%','fa-chart-line'],['Overdue rate',($taskSummary['total'] ? round($taskSummary['overdue']/$taskSummary['total']*100,1) : 0).'%','fa-triangle-exclamation'],['Critical tasks',$taskSummary['critical'],'fa-fire'],['Blocked tasks',$taskSummary['blocked'],'fa-ban']] as [$label,$value,$icon])<article class="blade-dashboard-kpi tm-dashboard-stat"><span class="tm-stat-icon"><i class="fa-solid {{ $icon }}"></i></span><small>{{ $label }}</small><strong>{{ $value }}</strong></article>@endforeach</section>
    <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Efficiency</span><h2>Completion by assignee</h2></div></div>@forelse($taskWorkload as $row)<div class="tm-workload-row"><span class="wl-name">{{ $row['user']?->name }}</span><div class="tm-wl-bar"><i class="tm-wl-seg is-complete" style="width:{{ $row['total'] ? $row['completed']/$row['total']*100 : 0 }}%"></i></div><b>{{ $row['total'] ? round($row['completed']/$row['total']*100) : 0 }}%</b></div>@empty<p class="tm-empty-copy">No assignee performance is available.</p>@endforelse</article>
@elseif ($scope === 'templates')
    <div class="tm-dashboard-heading"><div><h1>Task Templates</h1><p>Approved reusable workflows from System Settings.</p></div></div>
    <section class="tm-tpl-grid">@forelse($taskTemplates as $template)<article class="tm-tpl-card"><span class="tm-tpl-ic"><i class="fa-solid fa-clone"></i></span><div class="tm-template-title"><h3>{{ $template['name'] ?? 'Task template' }}</h3><span class="blade-status-pill">{{ $template['cat'] ?? 'General' }}</span></div><p>{{ $template['desc'] ?? 'Reusable task workflow.' }}</p><ol>@foreach(($template['steps'] ?? []) as $step)<li>{{ $step }}</li>@endforeach</ol>@if($canCreateTask)<a class="blade-primary-action" href="{{ route('collaboration.tasks.index',$taskQuery(['scope'=>'all','create'=>1,'template'=>$template['id'] ?? null])) }}"><i class="fa-solid fa-play"></i> Use template</a>@endif</article>@empty<article class="blade-dashboard-card"><p class="tm-empty-copy">No approved task templates are available.</p></article>@endforelse</section>
@else
    @php
        $settingsTab = $filters['settings_tab'] ?? 'statuses';
    @endphp
    <div class="tm-dashboard-heading"><div><h1>Task Settings</h1><p>Statuses, workflow rules, permissions and notifications.</p></div><a class="tm-tbtn" href="{{ route('settings.system-settings.index',['setting_key'=>'collaboration.task_settings']) }}"><i class="fa-solid fa-gear"></i> Manage settings</a></div>
    <nav class="tm-settings-tabs" aria-label="Task settings">@foreach(['statuses'=>'Statuses','workflow'=>'Workflow','permissions'=>'Permissions','notifications'=>'Notifications'] as $key=>$label)<a class="{{ $settingsTab===$key ? 'on' : '' }}" href="{{ route('collaboration.tasks.index',$taskQuery(['scope'=>'settings','settings_tab'=>$key])) }}">{{ $label }}</a>@endforeach</nav>
    @if($settingsTab==='statuses')
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Workflow statuses</span><h2>Task lifecycle mapping</h2></div><small>{{ $taskSetting ? 'Version '.$taskSetting->version : 'Safe defaults' }}</small></div><div class="tm-status-settings">@foreach($statuses as $value=>$label)@php $column=\App\Domain\Collaboration\TaskLifecycle::boardColumn($value,true,$value==='waiting_approval'); @endphp<div><i class="fa-solid fa-grip-vertical"></i><span class="blade-status-pill">{{ $label }}</span><small>maps to <b>{{ str_replace('_',' ',ucfirst($column)) }}</b> column</small></div>@endforeach</div></article>
    @elseif($settingsTab==='workflow')
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Workflow</span><h2>Active task rules</h2></div></div><div class="tm-workflow-settings">@foreach(['auto_progress'=>['Auto-calculate progress','Parent task progress rolls up from subtasks and checklist'], 'require_completion_approval'=>['Require approval to complete','Selected tasks need approver sign-off'], 'lock_completed'=>['Lock completed tasks','Prevent edits after completion'], 'transfer_requires_approval'=>['Transfer needs approval','Manager approves before reassignment'], 'auto_archive_days'=>['Automatic archive','Move completed tasks to archive after the configured period']] as $key=>[$label,$sub])<div><span><b>{{ $label }}</b><small>{{ $sub }}</small></span><em class="tm-setting-toggle {{ data_get($taskSetting?->value,$key,false) ? 'on' : '' }}" aria-label="{{ data_get($taskSetting?->value,$key,false) ? 'Enabled' : 'Disabled' }}"></em></div>@endforeach</div></article>
    @elseif($settingsTab==='permissions')
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Role permission matrix</span><h2>Effective task access</h2></div></div><div class="tm-permission-scroll"><table class="tm-permission-table"><thead><tr><th>Role</th>@foreach(['view','create','edit','assign','transfer','approve','archive','export','comment'] as $ability)<th>{{ ucfirst($ability) }}</th>@endforeach</tr></thead><tbody>@foreach($taskPermissionMatrix as $row)<tr><th>{{ $row['role'] }}</th>@foreach(['view','create','edit','assign','transfer','approve','archive','export','comment'] as $ability)<td>@if($row[$ability]==='all')<i class="fa-solid fa-check is-yes" aria-label="Allowed"></i>@elseif($row[$ability]==='own')<span class="tm-own-pill">Own</span>@else<i class="fa-solid fa-xmark is-no" aria-label="Not allowed"></i>@endif</td>@endforeach</tr>@endforeach</tbody></table></div></article>
    @else
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Notifications</span><h2>Task notification rules</h2></div></div><div class="tm-workflow-settings">@foreach(['notify_assigned'=>['Task assigned to me','When someone assigns me a task'], 'notify_mentions'=>['Comments and mentions','When I am mentioned or a watched task receives a comment'], 'notify_due_soon'=>['Due soon','Reminder before a task is due'], 'notify_overdue'=>['Overdue alerts','When an open task passes its due date']] as $key=>[$label,$sub])<div><span><b>{{ $label }}</b><small>{{ $sub }}</small></span><em class="tm-setting-toggle {{ data_get($taskSetting?->value,$key,true) ? 'on' : '' }}" aria-label="{{ data_get($taskSetting?->value,$key,true) ? 'Enabled' : 'Disabled' }}"></em></div>@endforeach</div></article>
    @endif
@endif
</div>
