@extends('layouts.builder360-classic')
@section('title', 'Employee Movements - Builder360 ERP-CRM')
@section('content')
<x-hr.people-workspace
    title="Employee Movements"
    :description="$employee->employee_code.' - '.$employee->name.' - '.$employee->designation"
    eyebrow="People / Employee 360"
    active="employees"
>
    <x-slot:actions><a class="people-button" href="{{ route('hr.employees.index') }}"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i> Employee directory</a></x-slot:actions>
    @if(session('status'))<section class="blade-alert blade-alert-success" role="status">{{ session('status') }}</section>@endif
    @if($errors->any())<section class="blade-alert blade-alert-danger" role="alert" tabindex="-1"><strong>Please correct the highlighted movement fields.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif
    <x-hr.employee-profile-navigation :links="$profileNavigation" active="movements" />
    @if($abilities['canCreate'])
    <section class="blade-card" x-data="{ movementType: '{{ old('movement_type','transfer') }}' }"><div class="blade-card-header"><div><p class="blade-eyebrow">Effective-dated change</p><h2>Create employee movement</h2></div></div>
        <form method="POST" action="{{ route('hr.employees.movements.store',$employee) }}" class="blade-form-grid">@csrf
            <label>Movement type<select name="movement_type" x-model="movementType" required>@foreach(['transfer'=>'Transfer','promotion'=>'Promotion','department_change'=>'Department change','reporting_change'=>'Reporting change','salary_change'=>'Salary change','status_change'=>'Status change','grade_change'=>'Grade change'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label>Effective on<input type="date" name="effective_on" value="{{ old('effective_on',now()->toDateString()) }}" required></label><input type="hidden" name="status" value="pending">
            <label x-show="movementType === 'transfer'">Branch<select name="new_values[branch_id]" :disabled="movementType !== 'transfer'"><option value="">No branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} &middot; {{ $branch->name }}</option>@endforeach</select></label>
            <label x-show="movementType === 'transfer'">Project<select name="new_values[project_id]" :disabled="movementType !== 'transfer'"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->code }} &middot; {{ $project->name }}</option>@endforeach</select></label>
            <label x-show="movementType === 'transfer' || movementType === 'department_change'">Department<input name="new_values[department]" :disabled="!['transfer','department_change'].includes(movementType)" value="{{ old('new_values.department',$employee->department) }}"></label>
            <label x-show="movementType === 'promotion'">Designation<input name="new_values[designation]" :disabled="movementType !== 'promotion'" value="{{ old('new_values.designation',$employee->designation) }}"></label>
            <label x-show="movementType === 'promotion' || movementType === 'grade_change'">Grade<input name="new_values[grade]" :disabled="!['promotion','grade_change'].includes(movementType)" value="{{ old('new_values.grade',$employee->grade) }}"></label>
            <label x-show="movementType === 'promotion' || movementType === 'salary_change'">Monthly CTC<input type="number" min="0" step="0.01" name="new_values[monthly_ctc]" :disabled="!['promotion','salary_change'].includes(movementType)" value="{{ old('new_values.monthly_ctc',$employee->monthly_ctc) }}"></label>
            <label x-show="movementType === 'reporting_change'">Reporting manager<select name="new_values[manager_employee_id]" :disabled="movementType !== 'reporting_change'"><option value="">No reporting manager</option>@foreach($managers as $manager)<option value="{{ $manager->id }}">{{ $manager->employee_code }} &middot; {{ $manager->name }}</option>@endforeach</select></label>
            <label x-show="movementType === 'status_change'">Employment status<select name="new_values[status]" :disabled="movementType !== 'status_change'">@foreach(['active'=>'Active','inactive'=>'Inactive','on_notice'=>'On notice','separated'=>'Separated'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label>
            <label class="blade-form-wide">Reason<textarea name="reason" maxlength="2000" required>{{ old('reason') }}</textarea></label><label class="blade-form-wide">Remarks<textarea name="remarks" maxlength="2000">{{ old('remarks') }}</textarea></label><button class="blade-primary-action">Submit movement</button>
        </form>
    </section>
    @endif
    <section class="blade-card"><div class="blade-card-header"><div><p class="blade-eyebrow">Movement register</p><h2>Effective-dated history</h2></div></div><form method="GET" action="{{ route('hr.employees.movements.index',$employee) }}" class="blade-filter-grid"><label>Type<select name="movement_type"><option value="">All types</option>@foreach(['transfer','promotion','department_change','reporting_change','salary_change','status_change','grade_change'] as $value)<option value="{{ $value }}" @selected(request('movement_type')===$value)>{{ str_replace('_',' ',ucfirst($value)) }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">All statuses</option>@foreach(['pending','approved','cancelled'] as $value)<option value="{{ $value }}" @selected(request('status')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></label><button class="blade-secondary-action">Apply filters</button></form>
        <div class="blade-table-wrap"><table class="blade-table"><caption class="sr-only">Effective-dated movement history for {{ $employee->name }}</caption><thead><tr><th scope="col">Movement</th><th scope="col">Type</th><th scope="col">Effective date</th><th scope="col">Changes</th><th scope="col">Created by</th><th scope="col">Status</th><th scope="col">Action</th></tr></thead><tbody>@forelse($movements as $movement) @php($actions=$movementActions[$movement->id]??[])<tr><td><strong>{{ $movement->number }}</strong><br><span>{{ $movement->reason }}</span></td><td>{{ $movement->typeLabel }}</td><td>{{ $movement->effectiveDate }}</td><td>@foreach($movement->changes as $change)<span>{{ $change->label }}: {{ $change->value }}</span><br>@endforeach @if($movement->hasRestrictedCompensation)<span>Compensation details: Restricted</span>@elseif($movement->changes === [])<span>No field changes recorded</span>@endif</td><td>{{ $movement->createdByName }}</td><td><span class="blade-status-pill">{{ $movement->statusLabel }}</span></td><td>@if($actions['canApprove']??false)<form method="POST" action="{{ route('hr.employees.movements.approve',[$employee,$movement->id]) }}" class="blade-inline-form">@csrf @method('PATCH')<label class="sr-only" for="movement-remarks-{{ $movement->id }}">Approval remarks for {{ $movement->number }}</label><input id="movement-remarks-{{ $movement->id }}" name="remarks" maxlength="2000" placeholder="Approval remarks"><button class="blade-primary-action" aria-label="Approve and apply movement {{ $movement->number }}">Approve and apply</button></form>@else<span>No action available</span>@endif</td></tr>@empty<tr><td colspan="7">No employee movements are available for the selected filters.</td></tr>@endforelse</tbody></table></div>{{ $movements->withQueryString()->links() }}</section>
</x-hr.people-workspace>
@endsection
