@extends('layouts.builder360-classic')
@section('title', 'Payroll Summary - Builder360 ERP-CRM')
@section('content')
<x-hr.people-workspace
    title="Payroll Summary"
    :description="$summary['employee']['employee_code'].' - '.$summary['employee']['name'].' - '.$summary['employee']['designation']"
    eyebrow="People / Employee 360"
    active="employees"
>
    <x-slot:actions><a class="people-button" href="{{ route('payroll.runs.index') }}"><i class="fa-solid fa-money-check-dollar" aria-hidden="true"></i> Payroll workspace</a></x-slot:actions>
    <x-hr.employee-profile-navigation :links="$profileNavigation" active="payroll" />
    <section class="blade-dashboard-kpis" aria-label="Payroll totals"><article class="blade-dashboard-card"><span>Payroll records</span><strong>{{ $summary['totals']['payroll_items_count'] }}</strong><small>Available pay periods</small></article><article class="blade-dashboard-card"><span>Gross earnings</span><strong>INR {{ number_format($summary['totals']['gross_earnings'],2) }}</strong><small>Across available records</small></article><article class="blade-dashboard-card"><span>Deductions</span><strong>INR {{ number_format($summary['totals']['total_deductions'],2) }}</strong><small>Across available records</small></article><article class="blade-dashboard-card"><span>Net payable</span><strong>INR {{ number_format($summary['totals']['net_payable'],2) }}</strong><small>Across available records</small></article></section>
    <section class="blade-card"><div class="blade-card-header"><div><p class="blade-eyebrow">Current assignment</p><h2>Salary structure</h2></div></div>@if($summary['current_assignment'])<dl class="blade-profile-list"><div><dt>Structure</dt><dd>{{ data_get($summary,'current_assignment.structure.code') }} &middot; {{ data_get($summary,'current_assignment.structure.name') }}</dd></div><div><dt>Version</dt><dd>{{ data_get($summary,'current_assignment.structure.version') }}</dd></div><div><dt>Effective from</dt><dd>{{ $summary['current_assignment']['effective_from'] }}</dd></div><div><dt>Status</dt><dd>{{ ucfirst($summary['current_assignment']['status']) }}</dd></div></dl>@else<p class="blade-workspace-note">No active salary assignment is available.</p>@endif</section>
    <section class="blade-card"><div class="blade-card-header"><div><p class="blade-eyebrow">Pay history</p><h2>Payroll records</h2></div></div><div class="blade-table-wrap"><table class="blade-table"><caption class="sr-only">Authorized payroll history for {{ $summary['employee']['name'] }}</caption><thead><tr><th scope="col">Run</th><th scope="col">Period</th><th scope="col">Payable days</th><th scope="col">Gross</th><th scope="col">Deductions</th><th scope="col">Net</th><th scope="col">Status</th></tr></thead><tbody>@forelse($summary['payroll_items'] as $item)<tr><td>{{ $item['run_number'] }}</td><td>{{ $item['period_month'] }}/{{ $item['period_year'] }}</td><td>{{ $item['payable_days'] }} / {{ $item['working_days'] }}</td><td>INR {{ number_format($item['gross_earnings'],2) }}</td><td>INR {{ number_format($item['total_deductions'],2) }}</td><td>INR {{ number_format($item['net_payable'],2) }}</td><td><span class="blade-status-pill">{{ ucfirst($item['status']) }}</span></td></tr>@empty<tr><td colspan="7">No payroll records are available.</td></tr>@endforelse</tbody></table></div></section>
    <section class="blade-card"><div class="blade-card-header"><div><p class="blade-eyebrow">Tax records</p><h2>Employee tax documents</h2></div></div><div class="blade-table-wrap"><table class="blade-table"><caption class="sr-only">Authorized tax document history for {{ $summary['employee']['name'] }}</caption><thead><tr><th scope="col">Document</th><th scope="col">Financial year</th><th scope="col">Gross salary</th><th scope="col">Taxable income</th><th scope="col">TDS</th><th scope="col">Status</th></tr></thead><tbody>@forelse($summary['tax_documents'] as $document)<tr><td>{{ $document['document_number'] }}<br><span>{{ str_replace('_',' ',ucfirst($document['document_type'])) }}</span></td><td>{{ $document['financial_year'] }}</td><td>INR {{ number_format($document['gross_salary'],2) }}</td><td>INR {{ number_format($document['taxable_income'],2) }}</td><td>INR {{ number_format($document['tds_deducted'],2) }}</td><td><span class="blade-status-pill">{{ ucfirst($document['status']) }}</span></td></tr>@empty<tr><td colspan="6">No tax documents are available.</td></tr>@endforelse</tbody></table></div></section>
</x-hr.people-workspace>
@endsection
