@extends('layouts.builder360-classic')
@section('title', 'Employee Profile Details - Builder360 ERP-CRM')
@section('content')
<x-hr.people-workspace
    title="Employee Profile Details"
    :description="$employee->employee_code.' - '.$employee->name.' - '.$employee->designation"
    eyebrow="People / Employee 360"
    active="employees"
>
    <x-slot:actions><a class="people-button" href="{{ route('hr.employees.index') }}"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i> Employee directory</a></x-slot:actions>
    @if(session('status'))<section class="blade-alert blade-alert-success" role="status">{{ session('status') }}</section>@endif
    @if($errors->any())<section class="blade-alert blade-alert-danger" role="alert" tabindex="-1"><strong>Please correct the highlighted profile fields.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif
    <x-hr.employee-profile-navigation :links="$profileNavigation" active="work-profile" />
    <section class="blade-card"><div class="blade-card-header"><div><p class="blade-eyebrow">Personal and employment context</p><h2>Profile sections</h2></div></div>
    @if($abilities['canUpdate'])<form method="POST" action="{{ route('hr.employees.profile-sections.update',$employee) }}" class="blade-form-grid" x-data="{ emergency: {{ data_get($sections,'emergency.0.name') ? 'true' : 'false' }}, family: {{ data_get($sections,'family.0.name') ? 'true' : 'false' }}, education: {{ data_get($sections,'education.0.qualification') ? 'true' : 'false' }}, experience: {{ data_get($sections,'experience.0.company') ? 'true' : 'false' }} }">@csrf @method('PATCH')
        <label>Date of birth<input type="date" name="sections[personal][dob]" value="{{ old('sections.personal.dob',data_get($sections,'personal.dob')) }}" max="{{ now()->subDay()->toDateString() }}"></label><label>Gender<input name="sections[personal][gender]" value="{{ old('sections.personal.gender',data_get($sections,'personal.gender')) }}" maxlength="40"></label><label>Marital status<input name="sections[personal][marital]" value="{{ old('sections.personal.marital',data_get($sections,'personal.marital')) }}" maxlength="40"></label><label>Blood group<input name="sections[personal][blood]" value="{{ old('sections.personal.blood',data_get($sections,'personal.blood')) }}" maxlength="10"></label><label>Mobile<input name="sections[personal][mobile]" value="{{ old('sections.personal.mobile',data_get($sections,'personal.mobile')) }}" maxlength="30"></label><label>Personal email<input type="email" name="sections[personal][email]" value="{{ old('sections.personal.email',data_get($sections,'personal.email')) }}"></label>
        <label class="blade-form-wide"><input type="checkbox" x-model="emergency"> Add emergency contact</label><label x-show="emergency">Emergency contact name<input name="sections[emergency][0][name]" :disabled="!emergency" value="{{ old('sections.emergency.0.name',data_get($sections,'emergency.0.name')) }}" maxlength="120"></label><label x-show="emergency">Emergency relation<input name="sections[emergency][0][relation]" :disabled="!emergency" value="{{ old('sections.emergency.0.relation',data_get($sections,'emergency.0.relation')) }}" maxlength="80"></label><label x-show="emergency">Emergency phone<input name="sections[emergency][0][phone]" :disabled="!emergency" value="{{ old('sections.emergency.0.phone',data_get($sections,'emergency.0.phone')) }}" maxlength="30"></label>
        <label class="blade-form-wide"><input type="checkbox" x-model="family"> Add family member</label><label x-show="family">Family member<input name="sections[family][0][name]" :disabled="!family" value="{{ old('sections.family.0.name',data_get($sections,'family.0.name')) }}" maxlength="120"></label><label x-show="family">Family relation<input name="sections[family][0][relation]" :disabled="!family" value="{{ old('sections.family.0.relation',data_get($sections,'family.0.relation')) }}" maxlength="80"></label><label x-show="family">Dependent<select name="sections[family][0][dependent]" :disabled="!family"><option value="0">No</option><option value="1" @selected((bool)old('sections.family.0.dependent',data_get($sections,'family.0.dependent')))>Yes</option></select></label>
        <label class="blade-form-wide"><input type="checkbox" x-model="education"> Add education record</label><label x-show="education">Qualification<input name="sections[education][0][qualification]" :disabled="!education" value="{{ old('sections.education.0.qualification',data_get($sections,'education.0.qualification')) }}" maxlength="160"></label><label x-show="education">Institute<input name="sections[education][0][institute]" :disabled="!education" value="{{ old('sections.education.0.institute',data_get($sections,'education.0.institute')) }}" maxlength="180"></label><label x-show="education">Completion year<input type="number" min="1950" max="{{ now()->year+1 }}" name="sections[education][0][year]" :disabled="!education" value="{{ old('sections.education.0.year',data_get($sections,'education.0.year')) }}"></label>
        <label class="blade-form-wide"><input type="checkbox" x-model="experience"> Add prior experience</label><label x-show="experience">Previous company<input name="sections[experience][0][company]" :disabled="!experience" value="{{ old('sections.experience.0.company',data_get($sections,'experience.0.company')) }}" maxlength="180"></label><label x-show="experience">Previous role<input name="sections[experience][0][role]" :disabled="!experience" value="{{ old('sections.experience.0.role',data_get($sections,'experience.0.role')) }}" maxlength="160"></label><label x-show="experience">Experience from<input type="date" name="sections[experience][0][from]" :disabled="!experience" value="{{ old('sections.experience.0.from',data_get($sections,'experience.0.from')) }}"></label><label x-show="experience">Experience to<input type="date" name="sections[experience][0][to]" :disabled="!experience" value="{{ old('sections.experience.0.to',data_get($sections,'experience.0.to')) }}"></label>
        <button class="blade-primary-action">Save profile details</button>
    </form>@else<p class="blade-workspace-note">These profile details are available in read-only mode for your current access.</p><dl class="blade-profile-list">@foreach(($sections['personal']??[]) as $label=>$value)<div><dt>{{ str_replace('_',' ',ucfirst($label)) }}</dt><dd>{{ is_scalar($value)?$value:'Recorded' }}</dd></div>@endforeach</dl>@endif
    </section>
</x-hr.people-workspace>
@endsection
