<?php
namespace App\Http\Controllers\Possession;
use App\Application\Possession\Actions\CompletePossessionHandover; use App\Application\Possession\Actions\InitiatePossessionHandover; use App\Application\Possession\Actions\IssuePossessionLetter; use App\Application\Possession\Actions\ListHandoverSnagWorkspace; use App\Application\Possession\Actions\ListPossessionHandoverWorkspace; use App\Application\Possession\Actions\ReportHandoverSnag; use App\Application\Possession\Actions\ResolveHandoverSnag; use App\Application\Possession\Actions\UpdatePossessionChecklist; use App\Application\Possession\Data\PossessionCommandData;
use App\Http\Controllers\Controller; use App\Http\Requests\Possession\CompletePossessionHandoverRequest; use App\Http\Requests\Possession\HandoverSnagIndexRequest; use App\Http\Requests\Possession\IssuePossessionLetterRequest; use App\Http\Requests\Possession\PossessionHandoverIndexRequest; use App\Http\Requests\Possession\ResolveHandoverSnagRequest; use App\Http\Requests\Possession\StoreHandoverSnagRequest; use App\Http\Requests\Possession\StorePossessionHandoverRequest; use App\Http\Requests\Possession\UpdateHandoverChecklistRequest; use App\Http\Resources\HandoverSnagResource; use App\Http\Resources\PossessionHandoverResource; use App\Models\HandoverSnag; use App\Models\PossessionHandover; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Resources\Json\AnonymousResourceCollection; use Illuminate\View\View;
class PossessionHandoverController extends Controller
{
    public function handovers(PossessionHandoverIndexRequest $request,ListPossessionHandoverWorkspace $list): AnonymousResourceCollection|View { $w=$list->execute($request->user(),$request->validated()); return $request->wantsJson()?PossessionHandoverResource::collection($w->handovers):view('possession.handovers.index',$w->toView()); }
    public function storeHandover(StorePossessionHandoverRequest $request,InitiatePossessionHandover $initiate): PossessionHandoverResource|RedirectResponse { $h=$initiate->execute(new PossessionCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new PossessionHandoverResource($h))->additional(['message'=>'Possession handover initiated.']):redirect()->route('possession.handovers.index')->with('status',"Possession handover {$h->handover_number} initiated."); }
    public function updateChecklist(PossessionHandover $possessionHandover,UpdateHandoverChecklistRequest $request,UpdatePossessionChecklist $update): PossessionHandoverResource|RedirectResponse { $h=$update->execute($possessionHandover,new PossessionCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new PossessionHandoverResource($h))->additional(['message'=>'Handover checklist updated.']):redirect()->route('possession.handovers.index')->with('status',"Possession handover {$h->handover_number} checklist updated."); }
    public function issueLetter(PossessionHandover $possessionHandover,IssuePossessionLetterRequest $request,IssuePossessionLetter $issue): PossessionHandoverResource|RedirectResponse { $h=$issue->execute($possessionHandover,new PossessionCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new PossessionHandoverResource($h))->additional(['message'=>'Possession letter issued.']):redirect()->route('possession.handovers.index')->with('status',"Possession letter issued for {$h->handover_number}."); }
    public function completeHandover(PossessionHandover $possessionHandover,CompletePossessionHandoverRequest $request,CompletePossessionHandover $complete): PossessionHandoverResource|RedirectResponse { $h=$complete->execute($possessionHandover,new PossessionCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new PossessionHandoverResource($h))->additional(['message'=>'Possession handover completed.']):redirect()->route('possession.handovers.index')->with('status',"Possession handover {$h->handover_number} completed."); }
    public function snags(HandoverSnagIndexRequest $request,ListHandoverSnagWorkspace $list): AnonymousResourceCollection|View { $w=$list->execute($request->user(),$request->validated()); return $request->wantsJson()?HandoverSnagResource::collection($w->snags):view('possession.snags.index',$w->toView()); }
    public function storeSnag(StoreHandoverSnagRequest $request,ReportHandoverSnag $report): HandoverSnagResource|RedirectResponse { $s=$report->execute(new PossessionCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new HandoverSnagResource($s))->additional(['message'=>'Handover snag reported.']):redirect()->route('possession.snags.index')->with('status',"Handover snag {$s->snag_number} reported."); }
    public function resolveSnag(HandoverSnag $handoverSnag,ResolveHandoverSnagRequest $request,ResolveHandoverSnag $resolve): HandoverSnagResource|RedirectResponse { $s=$resolve->execute($handoverSnag,new PossessionCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new HandoverSnagResource($s))->additional(['message'=>'Handover snag resolved.']):redirect()->route('possession.snags.index')->with('status',"Handover snag {$s->snag_number} resolved."); }
}
