<div class="cal-body" x-ref="calendarBody" x-on:scroll.passive="rememberScroll">
<?php if($view==='month'): ?>
    <section class="cal-month"><div class="cal-month-grid">
        <?php $__currentLoopData = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $day): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cal-dow"><?php echo e($day); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        <?php $__currentLoopData = $calendarDays; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $day): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cal-cell <?php echo e(!$day['in_month']?'dim':''); ?> <?php echo e($day['date']->isToday()?'today':''); ?>"><span class="cal-cell-date"><?php echo e($day['date']->day); ?></span>
            <?php $__currentLoopData = $day['events']->take(4); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $event): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php echo $__env->make('collaboration.calendar-events.partials.event-pill',['event'=>$event], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            <?php if($day['events']->count()>4): ?><a class="cal-ev-more" href="<?php echo e(route('collaboration.calendar-events.index',$calendarQuery(['view'=>'list','date_from'=>$day['date']->toDateString(),'date_to'=>$day['date']->toDateString(),'page'=>null]))); ?>">+<?php echo e($day['events']->count()-4); ?> more</a><?php endif; ?>
        </div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </div></section>
<?php elseif(in_array($view,['week','day'],true)): ?>
    <?php $hourHeight=52; $gridHeight=count($calendarHours)*$hourHeight; $nowLocal=now($calendarTimezone); ?>
    <section class="cal-timegrid <?php echo e($view==='day'?'is-day':''); ?>">
        <div class="cal-tg-header" style="--cal-columns:<?php echo e($timedDays->count()); ?>"><div class="cal-tg-corner"></div><?php $__currentLoopData = $timedDays; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $day): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cal-tg-daycol <?php echo e($day['date']->isToday()?'today':''); ?>"><span class="dow"><?php echo e($day['date']->format('D')); ?></span><span class="dnum"><?php echo e($day['date']->format('d')); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
        <div class="cal-tg-stage" style="--cal-columns:<?php echo e($timedDays->count()); ?>;--cal-grid-height:<?php echo e($gridHeight); ?>px">
            <div class="cal-tg-times"><?php $__currentLoopData = $calendarHours; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $hour): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span style="height:<?php echo e($hourHeight); ?>px"><?php echo e(\Carbon\CarbonImmutable::createFromTime($hour)->format('g A')); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
            <?php $__currentLoopData = $timedDays; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $day): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cal-tg-daybody <?php echo e($day['date']->isToday()?'today':''); ?>" style="height:<?php echo e($gridHeight); ?>px">
                <?php $__currentLoopData = $calendarHours; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $hour): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><i class="cal-tg-hour" style="top:<?php echo e(($loop->index)*$hourHeight); ?>px"></i><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                <?php $__currentLoopData = $day['blocks']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $block): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $event=$block['event']; $width=100/max(1,$day['columns']); ?>
                    <a x-show="!categoryHidden('<?php echo e($eventTypeOf($event)); ?>')" class="cal-tg-event" href="<?php echo e(route('collaboration.calendar-events.index',$calendarQuery(['event_id'=>$event->id]))); ?>" style="top:<?php echo e($block['top']); ?>px;height:<?php echo e($block['height']); ?>px;left:calc(<?php echo e($block['column']*$width); ?>% + 3px);width:calc(<?php echo e($width); ?>% - 6px);background:<?php echo e($block['color']); ?>" title="<?php echo e($event->title); ?>"><time><?php echo e($block['local_start']->format('g:i A')); ?></time><b><?php echo e($event->title); ?></b></a>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                <?php if($day['date']->isToday() && $nowLocal->hour >= min($calendarHours) && $nowLocal->hour <= max($calendarHours)): ?><span class="cal-now-line" style="top:<?php echo e((($nowLocal->hour-min($calendarHours))*60+$nowLocal->minute)/60*$hourHeight); ?>px"></span><?php endif; ?>
            </div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </div>
    </section>
<?php elseif($view==='list'): ?>
    <section class="cal-list"><?php $__empty_1 = true; $__currentLoopData = $periodEvents->groupBy(fn($event)=>$event->starts_at?->setTimezone($calendarTimezone)->toDateString()); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $date=>$dayEvents): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
        <h2 class="cal-list-day"><?php echo e(\Illuminate\Support\Carbon::parse($date,$calendarTimezone)->format('D, d M Y')); ?></h2>
        <?php $__currentLoopData = $dayEvents; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $event): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $localStart=$event->starts_at?->setTimezone($calendarTimezone); $localEnd=$event->ends_at?->setTimezone($calendarTimezone); $type=$eventTypeOf($event); ?>
            <a x-show="!categoryHidden('<?php echo e($type); ?>')" class="cal-list-row" href="<?php echo e(route('collaboration.calendar-events.index',$calendarQuery(['event_id'=>$event->id]))); ?>"><span class="cal-list-time"><b class="t1"><?php echo e($localStart?->format('g:i A')); ?></b><small class="t2"><?php echo e(max(1,$localStart?->diffInMinutes($localEnd)??0)); ?> min</small></span><i class="cal-list-bar" style="background:<?php echo e($eventColors[$type]??'#64748b'); ?>"></i><span class="cal-list-main"><b class="cal-list-title"><?php echo e($event->title); ?></b><span class="cal-list-meta"><span class="m" style="color:<?php echo e($eventColors[$type]??'#64748b'); ?>"><i class="fa-regular fa-calendar"></i><?php echo e($eventTypes[$type]??str($type)->headline()); ?></span><span class="m"><i class="fa-solid fa-user"></i><?php echo e($event->organizer?->name); ?></span><?php if($event->project): ?><span class="m"><i class="fa-solid fa-building"></i><?php echo e($event->project->code); ?></span><?php endif; ?> <?php if($event->location): ?><span class="m"><i class="fa-solid fa-location-dot"></i><?php echo e($event->location); ?></span><?php endif; ?></span></span><span class="blade-status-pill"><?php echo e($statuses[$event->status]??$event->status); ?></span></a>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="cal-empty-state"><i class="fa-regular fa-calendar"></i><h2>No events found</h2><p>Create an event or adjust the selected filters.</p></div><?php endif; ?></section>
<?php else: ?>
    <?php $lanes=$view==='employee'?$employeeLanes:$teamLanes; ?>
    <section class="cal-lanes"><div class="cal-lanes-dow"><div class="cal-lane-corner"></div><?php for($offset=0;$offset<7;$offset++): ?><div class="<?php echo e($periodStart->addDays($offset)->isToday()?'today':''); ?>"><?php echo e($periodStart->addDays($offset)->format('D d')); ?></div><?php endfor; ?></div>
        <?php $__currentLoopData = $lanes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $lane): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cal-lane"><header class="cal-lane-head"><span class="tm-card-owner"><?php echo e(strtoupper(substr($lane['label'],0,1))); ?></span><span><b class="cal-lane-name"><?php echo e($lane['label']); ?></b><small class="cal-lane-sub"><?php echo e($lane['sub']); ?></small></span></header><div class="cal-lane-track"><?php for($offset=0;$offset<7;$offset++): ?><?php $laneDay=$periodStart->addDays($offset); ?><div class="cal-lane-cell <?php echo e($laneDay->isToday()?'today':''); ?>"><?php $__currentLoopData = $lane['events']->filter(fn($event)=>$event->starts_at?->setTimezone($calendarTimezone)->isSameDay($laneDay)); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $event): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $type=$eventTypeOf($event); ?><a x-show="!categoryHidden('<?php echo e($type); ?>')" class="cal-lane-pill" style="background:<?php echo e($eventColors[$type]??'#64748b'); ?>" href="<?php echo e(route('collaboration.calendar-events.index',$calendarQuery(['event_id'=>$event->id]))); ?>"><?php echo e($event->starts_at?->setTimezone($calendarTimezone)->format('g:i A')); ?> <?php echo e($event->title); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endfor; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </section>
<?php endif; ?>
</div>
<?php /**PATH /home/developer/public_html/build365/resources/views/collaboration/calendar-events/partials/views.blade.php ENDPATH**/ ?>