<div class="tm-body pad">
<?php if($scope === 'activity'): ?>
    <?php
        $activityFilter = $filters['activity_filter'] ?? 'all';
    ?>
    <div class="tm-dashboard-heading"><div><h1>Activity Center</h1><p>Every action across tasks available to your role.</p></div><nav class="tm-activity-filters" aria-label="Activity filters"><?php $__currentLoopData = ['all'=>'All','comments'=>'Comments','status'=>'Status','transfers'=>'Transfers','approvals'=>'Approvals','attachments'=>'Attachments','time'=>'Time']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="<?php echo e($activityFilter===$key ? 'on' : ''); ?>" href="<?php echo e(route('collaboration.tasks.index',$taskQuery(['scope'=>'activity','activity_filter'=>$key]))); ?>"><?php echo e($label); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></nav></div>
    <article class="blade-dashboard-card tm-insight-card">
        <?php $__empty_1 = true; $__currentLoopData = $taskActivity; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <a class="tm-act-row tm-act-<?php echo e($item['tone']); ?>" href="<?php echo e(route('collaboration.tasks.index',$taskQuery(['task_id'=>$item['task_id']]))); ?>">
                <span class="tm-act-ic"><i class="fa-solid <?php echo e($item['icon']); ?>"></i></span>
                <span><b><?php echo e($item['task_number']); ?></b> <?php echo e($item['label']); ?><small><?php echo e($item['actor'] ? $item['actor'].' · ' : ''); ?><?php echo e($item['task_title']); ?></small></span>
                <time datetime="<?php echo e($item['at']); ?>" title="<?php echo e($item['absolute_time']); ?>"><?php echo e($item['relative_time']); ?></time>
            </a>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
            <div class="tm-empty-panel"><span class="tm-empty-ic"><i class="fa-solid fa-wave-square"></i></span><span><b>No <?php echo e($activityFilter === 'all' ? '' : $activityFilter.' '); ?>activity</b><small>Task updates matching this filter will appear here.</small></span></div>
        <?php endif; ?>
    </article>
<?php elseif($scope === 'reports'): ?>
    <div class="tm-dashboard-heading"><div><h1>Reports</h1><p>Reports calculated from all tasks available to your role.</p></div><div class="tm-action-row"><a class="tm-tbtn" href="<?php echo e(route('collaboration.tasks.export',$taskQuery(['format'=>'csv']))); ?>"><i class="fa-solid fa-download"></i> Export CSV</a><a class="tm-tbtn" href="<?php echo e(route('collaboration.tasks.export',$taskQuery(['format'=>'pdf']))); ?>"><i class="fa-solid fa-file-pdf"></i> Export PDF</a></div></div>
    <section class="tm-dash-grid"><?php $__currentLoopData = [['Task Completion',$taskSummary['completed'].' completed of '.$taskSummary['total'],'fa-circle-check'],['Task Aging',$taskSummary['overdue'].' overdue task(s)','fa-clock'],['Approval Queue',$taskSummary['awaiting_approval'].' awaiting approval','fa-shield-halved'],['Critical Work',$taskSummary['critical'].' critical task(s)','fa-fire']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$title,$sub,$icon]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="tm-tpl-card"><span class="tm-tpl-ic"><i class="fa-solid <?php echo e($icon); ?>"></i></span><h3><?php echo e($title); ?></h3><p><?php echo e($sub); ?></p></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></section>
<?php elseif($scope === 'analytics'): ?>
    <div class="tm-dashboard-heading"><div><h1>Analytics</h1><p>Performance calculated from status, due dates and workflow records.</p></div></div>
    <section class="tm-dash-grid"><?php $__currentLoopData = [['Completion rate',$taskSummary['completion_rate'].'%','fa-chart-line'],['Overdue rate',($taskSummary['total'] ? round($taskSummary['overdue']/$taskSummary['total']*100,1) : 0).'%','fa-triangle-exclamation'],['Critical tasks',$taskSummary['critical'],'fa-fire'],['Blocked tasks',$taskSummary['blocked'],'fa-ban']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$label,$value,$icon]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="blade-dashboard-kpi tm-dashboard-stat"><span class="tm-stat-icon"><i class="fa-solid <?php echo e($icon); ?>"></i></span><small><?php echo e($label); ?></small><strong><?php echo e($value); ?></strong></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></section>
    <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Efficiency</span><h2>Completion by assignee</h2></div></div><?php $__empty_1 = true; $__currentLoopData = $taskWorkload; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="tm-workload-row"><span class="wl-name"><?php echo e($row['user']?->name); ?></span><div class="tm-wl-bar"><i class="tm-wl-seg is-complete" style="width:<?php echo e($row['total'] ? $row['completed']/$row['total']*100 : 0); ?>%"></i></div><b><?php echo e($row['total'] ? round($row['completed']/$row['total']*100) : 0); ?>%</b></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="tm-empty-copy">No assignee performance is available.</p><?php endif; ?></article>
<?php elseif($scope === 'templates'): ?>
    <div class="tm-dashboard-heading"><div><h1>Task Templates</h1><p>Approved reusable workflows from System Settings.</p></div></div>
    <section class="tm-tpl-grid"><?php $__empty_1 = true; $__currentLoopData = $taskTemplates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $template): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="tm-tpl-card"><span class="tm-tpl-ic"><i class="fa-solid fa-clone"></i></span><div class="tm-template-title"><h3><?php echo e($template['name'] ?? 'Task template'); ?></h3><span class="blade-status-pill"><?php echo e($template['cat'] ?? 'General'); ?></span></div><p><?php echo e($template['desc'] ?? 'Reusable task workflow.'); ?></p><ol><?php $__currentLoopData = ($template['steps'] ?? []); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $step): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($step); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ol><?php if($canCreateTask): ?><a class="blade-primary-action" href="<?php echo e(route('collaboration.tasks.index',$taskQuery(['scope'=>'all','create'=>1,'template'=>$template['id'] ?? null]))); ?>"><i class="fa-solid fa-play"></i> Use template</a><?php endif; ?></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><article class="blade-dashboard-card"><p class="tm-empty-copy">No approved task templates are available.</p></article><?php endif; ?></section>
<?php else: ?>
    <?php
        $settingsTab = $filters['settings_tab'] ?? 'statuses';
    ?>
    <div class="tm-dashboard-heading"><div><h1>Task Settings</h1><p>Statuses, workflow rules, permissions and notifications.</p></div><a class="tm-tbtn" href="<?php echo e(route('settings.system-settings.index',['setting_key'=>'collaboration.task_settings'])); ?>"><i class="fa-solid fa-gear"></i> Manage settings</a></div>
    <nav class="tm-settings-tabs" aria-label="Task settings"><?php $__currentLoopData = ['statuses'=>'Statuses','workflow'=>'Workflow','permissions'=>'Permissions','notifications'=>'Notifications']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="<?php echo e($settingsTab===$key ? 'on' : ''); ?>" href="<?php echo e(route('collaboration.tasks.index',$taskQuery(['scope'=>'settings','settings_tab'=>$key]))); ?>"><?php echo e($label); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></nav>
    <?php if($settingsTab==='statuses'): ?>
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Workflow statuses</span><h2>Task lifecycle mapping</h2></div><small><?php echo e($taskSetting ? 'Version '.$taskSetting->version : 'Safe defaults'); ?></small></div><div class="tm-status-settings"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $column=\App\Domain\Collaboration\TaskLifecycle::boardColumn($value,true,$value==='waiting_approval'); ?><div><i class="fa-solid fa-grip-vertical"></i><span class="blade-status-pill"><?php echo e($label); ?></span><small>maps to <b><?php echo e(str_replace('_',' ',ucfirst($column))); ?></b> column</small></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></article>
    <?php elseif($settingsTab==='workflow'): ?>
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Workflow</span><h2>Active task rules</h2></div></div><div class="tm-workflow-settings"><?php $__currentLoopData = ['auto_progress'=>['Auto-calculate progress','Parent task progress rolls up from subtasks and checklist'], 'require_completion_approval'=>['Require approval to complete','Selected tasks need approver sign-off'], 'lock_completed'=>['Lock completed tasks','Prevent edits after completion'], 'transfer_requires_approval'=>['Transfer needs approval','Manager approves before reassignment'], 'auto_archive_days'=>['Automatic archive','Move completed tasks to archive after the configured period']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>[$label,$sub]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div><span><b><?php echo e($label); ?></b><small><?php echo e($sub); ?></small></span><em class="tm-setting-toggle <?php echo e(data_get($taskSetting?->value,$key,false) ? 'on' : ''); ?>" aria-label="<?php echo e(data_get($taskSetting?->value,$key,false) ? 'Enabled' : 'Disabled'); ?>"></em></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></article>
    <?php elseif($settingsTab==='permissions'): ?>
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Role permission matrix</span><h2>Effective task access</h2></div></div><div class="tm-permission-scroll"><table class="tm-permission-table"><thead><tr><th>Role</th><?php $__currentLoopData = ['view','create','edit','assign','transfer','approve','archive','export','comment']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $ability): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><th><?php echo e(ucfirst($ability)); ?></th><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr></thead><tbody><?php $__currentLoopData = $taskPermissionMatrix; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><th><?php echo e($row['role']); ?></th><?php $__currentLoopData = ['view','create','edit','assign','transfer','approve','archive','export','comment']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $ability): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><td><?php if($row[$ability]==='all'): ?><i class="fa-solid fa-check is-yes" aria-label="Allowed"></i><?php elseif($row[$ability]==='own'): ?><span class="tm-own-pill">Own</span><?php else: ?><i class="fa-solid fa-xmark is-no" aria-label="Not allowed"></i><?php endif; ?></td><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div></article>
    <?php else: ?>
        <article class="blade-dashboard-card tm-insight-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Notifications</span><h2>Task notification rules</h2></div></div><div class="tm-workflow-settings"><?php $__currentLoopData = ['notify_assigned'=>['Task assigned to me','When someone assigns me a task'], 'notify_mentions'=>['Comments and mentions','When I am mentioned or a watched task receives a comment'], 'notify_due_soon'=>['Due soon','Reminder before a task is due'], 'notify_overdue'=>['Overdue alerts','When an open task passes its due date']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>[$label,$sub]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div><span><b><?php echo e($label); ?></b><small><?php echo e($sub); ?></small></span><em class="tm-setting-toggle <?php echo e(data_get($taskSetting?->value,$key,true) ? 'on' : ''); ?>" aria-label="<?php echo e(data_get($taskSetting?->value,$key,true) ? 'Enabled' : 'Disabled'); ?>"></em></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></article>
    <?php endif; ?>
<?php endif; ?>
</div>
<?php /**PATH /home/developer/public_html/build365/resources/views/collaboration/tasks/partials/insights.blade.php ENDPATH**/ ?>