<div class="tm-modal-scrim" x-show="createOpen" x-cloak role="presentation">
<section class="tm-modal cal-event-modal" role="dialog" aria-modal="true" aria-labelledby="calendar-create-title">
    <header class="tm-modal-head"><div class="cal-modal-title"><span><i class="fa-regular fa-calendar-plus"></i></span><h2 id="calendar-create-title">New event</h2></div><button type="button" class="tm-iconbtn" x-on:click="closeCreate" aria-label="Close event form"><i class="fa-solid fa-xmark"></i></button></header>
    <?php if($canCreateEvent): ?><form method="POST" action="<?php echo e(route('collaboration.calendar-events.store')); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?>
        <input type="hidden" name="client_token" value="<?php echo e(old('client_token', (string) \Illuminate\Support\Str::uuid())); ?>"><input type="hidden" name="timezone" value="<?php echo e(old('timezone',$calendarTimezone)); ?>">
        <div class="tm-modal-body"><div class="tm-form-grid">
            <?php if($companies->count()>1): ?><?php if (isset($component)) { $__componentOriginal5ee006ce6757c21855df609df2a8580f = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal5ee006ce6757c21855df609df2a8580f = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.forms.company-context','data' => ['companies' => $companies,'placeholder' => 'Auto from project or attendee']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('forms.company-context'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['companies' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute($companies),'placeholder' => 'Auto from project or attendee']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal5ee006ce6757c21855df609df2a8580f)): ?>
<?php $attributes = $__attributesOriginal5ee006ce6757c21855df609df2a8580f; ?>
<?php unset($__attributesOriginal5ee006ce6757c21855df609df2a8580f); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal5ee006ce6757c21855df609df2a8580f)): ?>
<?php $component = $__componentOriginal5ee006ce6757c21855df609df2a8580f; ?>
<?php unset($__componentOriginal5ee006ce6757c21855df609df2a8580f); ?>
<?php endif; ?><?php endif; ?>
            <label class="tm-field full"><span>Event title *</span><input class="tm-input" name="title" maxlength="255" required value="<?php echo e(old('title')); ?>" placeholder="e.g. Site visit — Rohit Agarwal"></label>
            <label class="tm-field"><span>Event type</span><select class="tm-select" name="event_type" required><?php $__currentLoopData = $eventTypes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('event_type','meeting')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="tm-field"><span>Priority</span><select class="tm-select" name="metadata[priority]"><?php $__currentLoopData = ['low'=>'Low','medium'=>'Medium','high'=>'High','urgent'=>'Critical']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('metadata.priority','medium')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="tm-field"><span>Start *</span><input class="tm-input" type="datetime-local" name="starts_at" value="<?php echo e(old('starts_at',$focusDate->setTime(11,0)->format('Y-m-d\TH:i'))); ?>" required></label>
            <label class="tm-field"><span>End *</span><input class="tm-input" type="datetime-local" name="ends_at" value="<?php echo e(old('ends_at',$focusDate->setTime(12,0)->format('Y-m-d\TH:i'))); ?>" required></label>
            <label class="tm-field"><span>Status</span><select class="tm-select" name="status"><option value="scheduled">Scheduled</option><option value="rescheduled">Rescheduled</option></select></label>
            <label class="tm-field"><span>Project</span><select class="tm-select" name="project_id"><option value="">No project</option><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($project->id); ?>" <?php if(old('project_id')==$project->id): echo 'selected'; endif; ?>><?php echo e($project->code); ?> · <?php echo e($project->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <fieldset class="tm-field full people-search-picker cal-attendee-picker" x-data="peopleSearch"><legend>Assigned employees</legend><label class="tm-search people-search-input"><i class="fa-solid fa-magnifying-glass"></i><input type="search" placeholder="Search employee name, team or role..." x-on:input="filterPeople($event)" oninput="if (window.filterPeople) window.filterPeople(event);"></label><div class="people-search-results people-search-multi"><?php $__currentLoopData = $calendarUsers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index=>$userOption): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><label data-person-search="<?php echo e(strtolower($userOption->name.' '.$userOption->email.' '.($userOption->role?->name??'').' '.($userOption->employee?->department??''))); ?>"><input type="checkbox" name="attendees[<?php echo e($index); ?>][user_id]" value="<?php echo e($userOption->id); ?>" <?php if(collect(old('attendees',[]))->pluck('user_id')->contains($userOption->id)): echo 'checked'; endif; ?>><span><b><?php echo e($userOption->name); ?></b><small><?php echo e($userOption->role?->name); ?> · <?php echo e($userOption->employee?->department ?? $userOption->email); ?></small></span></label><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></fieldset>
            <label class="tm-field"><span>Location</span><input class="tm-input" name="location" maxlength="255" value="<?php echo e(old('location')); ?>" placeholder="Office / site address"></label>
            <label class="tm-field"><span>Online meeting link</span><input class="tm-input" type="url" name="meeting_url" maxlength="1024" value="<?php echo e(old('meeting_url')); ?>" placeholder="https://meet..."></label>
            <label class="tm-field"><span>Reminder</span><select class="tm-select" name="reminders[0][minutes_before]"><?php $__currentLoopData = [0=>'At event time',10=>'10 min before',15=>'15 min before',30=>'30 min before',60=>'1 hour before',1440=>'1 day before']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('reminders.0.minutes_before',15)==$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="tm-field"><span>Recurrence</span><select class="tm-select" name="recurrence[frequency]"><?php $__currentLoopData = ['none'=>'Does not repeat','daily'=>'Daily','weekly'=>'Weekly','monthly'=>'Monthly','yearly'=>'Yearly']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('recurrence.frequency','none')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="tm-field full"><span>Description / notes</span><textarea class="tm-textarea" name="description" maxlength="5000" placeholder="Agenda, context, talking points..."><?php echo e(old('description')); ?></textarea></label>
            <details class="cal-create-advanced full"><summary>Advanced options</summary><div class="tm-form-grid">
                <label class="tm-field full"><span>External guest emails</span><textarea class="tm-textarea is-compact" name="guest_emails" placeholder="guest@company.com, another@company.com"><?php echo e(old('guest_emails')); ?></textarea><small>Guests receive a secure invitation without Builder360 access.</small></label>
                <label class="tm-field"><span>Repeat interval</span><input class="tm-input" type="number" min="1" max="52" name="recurrence[interval]" value="<?php echo e(old('recurrence.interval',1)); ?>"></label>
                <label class="tm-field"><span>Repeat until</span><input class="tm-input" type="date" name="recurrence[until_at]" value="<?php echo e(old('recurrence.until_at')); ?>"></label>
                <label class="tm-field"><span>Visibility</span><select class="tm-select" name="visibility"><option value="internal" <?php if(old('visibility','internal')==='internal'): echo 'selected'; endif; ?>>Internal</option><option value="private" <?php if(old('visibility')==='private'): echo 'selected'; endif; ?>>Private</option></select></label>
                <label class="tm-field"><span>Timezone</span><input class="tm-input" value="<?php echo e($calendarTimezone); ?>" disabled><small>Times are saved securely in UTC.</small></label>
                <label class="tm-field full"><span>Attachments</span><input class="tm-input" type="file" name="attachments[]" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt"></label>
            </div></details>
        </div></div>
        <footer class="tm-modal-foot"><span class="tm-modal-note"><i class="fa-solid fa-shield-halved"></i> No conflicts detected yet</span><button type="button" class="blade-secondary-action" x-on:click="closeCreate">Cancel</button><button class="blade-primary-action" type="submit"><i class="fa-solid fa-plus"></i> Create event</button></footer>
    </form><?php else: ?><div class="tm-modal-body"><p class="tm-empty-copy">Event creation is not available for this role.</p></div><?php endif; ?>
</section></div>
<?php /**PATH /home/developer/public_html/build365/resources/views/collaboration/calendar-events/partials/create-modal.blade.php ENDPATH**/ ?>