@php
    $draft=$composeInternalDraft;
    $externalDraft=$composeExternalDraft ?? null;
    $activeDraft=$draft ?? $externalDraft;
    $context=$composeContext ?? [];
    $token=old('client_token',$activeDraft?->client_token ?? (string)Illuminate\Support\Str::uuid());
    $contextRecipients=collect($context['recipients'] ?? [])->mapWithKeys(fn($row)=>[$row['user']->id=>$row['type']])->all();
    $draftRecipients=$draft?->recipients?->mapWithKeys(fn($row)=>[$row->user_id=>$row->recipient_type])->all() ?? $contextRecipients;
    $senderKey=old('sender_key',$externalDraft ? 'external:'.$externalDraft->mailbox_account_id : request('sender_key','internal'));
    $composeOpen=$activeDraft || $errors->any() || request()->boolean('compose') || !empty($context);
@endphp
<details class="b360-mail-compose b360-unified-compose" x-data="unifiedMailboxComposer" data-initial-sender="{{ $senderKey }}" data-autosave-url="{{ route('mailbox.compose.store') }}" data-lock-version="{{ $activeDraft?->lock_version }}" data-draft-id="{{ $activeDraft?->id }}" data-draft-source="{{ $draft ? 'internal' : ($externalDraft ? 'external' : '') }}" data-internal-discard-template="{{ url('/mailbox/internal-drafts/__DRAFT__') }}" data-external-discard-template="{{ url('/mailbox/accounts/__ACCOUNT__/drafts/__DRAFT__') }}" @if($composeOpen) open @endif>
    <summary class="b360-mail-compose-btn"><i class="fa-solid fa-pen" aria-hidden="true"></i><span>Compose</span></summary>
    <div class="b360-mail-compose-panel" role="dialog" aria-modal="true" aria-labelledby="unified-compose-title">
        <header class="b360-unified-compose-head"><div><h2 id="unified-compose-title">{{ $context['title'] ?? ($activeDraft?'Continue draft':'New message') }}</h2><p x-text="deliveryDescription"></p></div><div><span class="b360-draft-status" x-text="status" aria-live="polite"></span><button type="button" class="b360-collab-icon-btn" x-on:click="minimize" aria-label="Minimize composer"><i class="fa-solid fa-minus"></i></button><button type="button" class="b360-collab-icon-btn" x-on:click="toggleExpanded" x-bind:aria-label="expanded ? 'Restore composer size' : 'Expand composer'"><i class="fa-solid fa-up-right-and-down-left-from-center"></i></button><button type="button" class="b360-collab-icon-btn" x-on:click="requestClose" aria-label="Close composer"><i class="fa-solid fa-xmark"></i></button></div></header>
        @if($errors->any())<div class="b360-compose-errors" role="alert"><strong>Review the message details.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" enctype="multipart/form-data" action="{{ route('mailbox.compose.store') }}" class="b360-unified-compose-form" x-ref="form" x-on:submit="prepareSubmit">
            @csrf<input type="hidden" name="client_token" value="{{ $token }}"><input type="hidden" name="lock_version" value="{{ $activeDraft?->lock_version }}" x-ref="lockVersion"><input type="hidden" name="intent" value="send" x-ref="intent">
            <label class="b360-compose-field b360-compose-from"><span>From</span><select name="sender_key" x-model="senderKey" x-on:change="senderChanged"><option value="internal">Builder360 Internal</option>@foreach($externalAccounts as $account)<option value="external:{{ $account->id }}">{{ $account->name }} · {{ $account->email }}</option>@endforeach</select></label>

            <section class="b360-internal-recipient-field" x-show="internalMode" x-cloak>
                <div class="b360-compose-field-label"><span>Recipients</span><small x-text="selectedPeopleLabel"></small></div>
                <div class="b360-selected-people" x-show="selectedPeople.length > 0" x-cloak><template x-for="person in selectedPeople" x-bind:key="person.id"><span class="b360-person-chip"><span class="b360-person-chip-avatar" x-text="person.initials"></span><b x-text="person.name"></b><select x-bind:value="person.type" x-bind:data-person-id="person.id" x-on:change="changeRecipientType"><option value="to">To</option><option value="cc">CC</option><option value="bcc">BCC</option></select><button type="button" x-bind:data-person-id="person.id" x-on:click="removePerson" aria-label="Remove recipient"><i class="fa-solid fa-xmark"></i></button><input type="hidden" x-bind:name="person.type + '_user_ids[]'" x-bind:value="person.id" x-bind:disabled="!internalMode"></span></template></div>
                <label class="b360-people-search"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i><input type="search" x-model.debounce.150ms="peopleQuery" placeholder="Search employees by name, email, role or department" aria-label="Search employees"></label>
                <div class="b360-mail-people-options" role="listbox" aria-label="Available employees">
                    @foreach($users as $userOption) @continue($userOption->id===auth()->id())
                        @php $existingType=old('recipient_types.'.$userOption->id,$draftRecipients[$userOption->id]??null); @endphp
                        <label data-mail-person data-person-id="{{ $userOption->id }}" data-person-name="{{ $userOption->name }}" data-person-email="{{ $userOption->email }}" data-person-role="{{ $userOption->role?->name }}" data-person-search="{{ str($userOption->name.' '.$userOption->email.' '.($userOption->role?->name??'').' '.($userOption->employee?->department??'').' '.($userOption->employee?->designation??''))->lower() }}" @if($existingType)data-selected-type="{{ $existingType }}"@endif>
                            <input type="checkbox" x-on:change="togglePerson" @checked($existingType)><x-ui.user-avatar :user="$userOption" :label="$userOption->name" class="b360-mail-person-avatar" /><span><strong>{{ $userOption->name }}</strong><small>{{ $userOption->role?->name ?? 'Employee' }} · {{ $userOption->email }}</small></span><i class="fa-solid fa-check" aria-hidden="true"></i>
                        </label>
                    @endforeach
                    <p x-show="visiblePeopleCount === 0" x-cloak>No matching employees.</p>
                </div>
            </section>

            <section class="b360-external-recipients" x-show="!internalMode" x-cloak>
                <label class="b360-compose-field"><span>To</span><input name="to" list="unified-mailbox-contacts" x-bind:disabled="internalMode" value="{{ old('to',collect($externalDraft?->to_addresses)->join(', ')) }}" placeholder="name@example.com"></label>
                <div class="b360-compose-cc-grid"><label class="b360-compose-field"><span>CC</span><input name="cc" list="unified-mailbox-contacts" x-bind:disabled="internalMode" value="{{ old('cc',collect($externalDraft?->cc_addresses)->join(', ')) }}"></label><label class="b360-compose-field"><span>BCC</span><input name="bcc" list="unified-mailbox-contacts" x-bind:disabled="internalMode" value="{{ old('bcc',collect($externalDraft?->bcc_addresses)->join(', ')) }}"></label></div>
                <datalist id="unified-mailbox-contacts">@foreach($externalContacts as $contact)<option value="{{ $contact['email']??'' }}">{{ $contact['name']??$contact['email']??'' }}</option>@endforeach</datalist>
                <small>Separate multiple addresses with commas. Duplicate addresses are removed automatically.</small>
            </section>

            <div class="b360-compose-meta-grid"><label class="b360-compose-field"><span>Project</span><select name="project_id"><option value="">No project link</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int)old('project_id',$draft?->project_id)===$project->id)>{{ $project->code }} · {{ $project->name }}</option>@endforeach</select></label><label class="b360-compose-field"><span>Priority</span><select name="priority">@foreach($priorities as $value=>$label)<option value="{{ $value }}" @selected(old('priority',$draft?->priority??'normal')===$value)>{{ $label }}</option>@endforeach</select></label><label class="b360-compose-field"><span>Send later</span><input type="datetime-local" name="scheduled_for" value="{{ old('scheduled_for',$activeDraft?->scheduled_for?->format('Y-m-d\TH:i')) }}"></label></div>
            <label class="b360-compose-field"><span>Subject</span><input name="subject" maxlength="255" value="{{ old('subject',$draft?->subject ?? $externalDraft?->subject ?? ($context['subject'] ?? '')) }}" placeholder="Add a subject"></label>
            <section class="b360-compose-editor"><div class="b360-compose-formatbar" role="toolbar" aria-label="Message formatting"><button type="button" data-format="bold" x-on:click="formatBody" title="Bold"><i class="fa-solid fa-bold"></i></button><button type="button" data-format="italic" x-on:click="formatBody" title="Italic"><i class="fa-solid fa-italic"></i></button><button type="button" data-format="list" x-on:click="formatBody" title="Bulleted list"><i class="fa-solid fa-list-ul"></i></button><button type="button" data-format="link" x-on:click="formatBody" title="Link"><i class="fa-solid fa-link"></i></button></div><textarea name="body" rows="10" maxlength="200000" x-ref="body" placeholder="Write your message">{{ old('body',$draft?->body ?? $externalDraft?->text_body ?? ($context['body'] ?? '')) }}</textarea><small>Formatting is sanitized before delivery. Keyboard undo and redo remain available.</small></section>
            <section class="b360-compose-attachment-zone" x-on:dragover.prevent="dragging=true" x-on:dragleave.prevent="dragging=false" x-on:drop.prevent="dropAttachments" x-bind:class="dragging ? 'is-dragging' : ''"><label><i class="fa-solid fa-paperclip"></i><span>Attach files or drag them here</span><input type="file" name="attachments[]" multiple x-ref="attachments" x-on:change="selectAttachments" accept=".jpg,.jpeg,.png,.gif,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.zip"></label><small>Up to 10 files, 25 MB each.</small><div class="b360-compose-file-grid" x-show="selectedAttachments.length > 0" x-cloak><template x-for="file in selectedAttachments" x-bind:key="file.key"><article><template x-if="file.preview"><img x-bind:src="file.preview" alt=""></template><i class="fa-solid fa-file" x-show="!file.preview"></i><span><b x-text="file.name"></b><small x-text="file.sizeLabel"></small></span><button type="button" x-bind:data-file-key="file.key" x-on:click="removeAttachment" aria-label="Remove attachment"><i class="fa-solid fa-xmark"></i></button></article></template></div>@if($activeDraft?->attachments?->isNotEmpty())<div class="b360-compose-file-grid">@foreach($activeDraft->attachments as $file)<article><i class="fa-solid fa-file"></i><span><b>{{ $file->original_filename ?? $file->filename }}</b><small>{{ number_format($file->size_bytes/1024,1) }} KB</small></span><label><input type="checkbox" name="remove_attachment_ids[]" value="{{ $file->id }}"> Remove</label></article>@endforeach</div>@endif</section>
            <input type="hidden" name="parent_message_id" value="{{ old('parent_message_id',$draft?->parent_message_id ?? ($context['parent_message_id'] ?? null)) }}">
            <footer class="b360-unified-compose-actions"><button type="button" class="blade-danger-action" x-on:click="discard">Discard</button><span class="b360-upload-progress" x-show="uploadProgress > 0 && uploadProgress < 100" x-cloak><i x-bind:style="'width:'+uploadProgress+'%'"></i></span><button type="submit" class="blade-secondary-action" data-intent="draft" x-on:click="chooseIntent">Save draft</button><button type="submit" class="blade-secondary-action" data-intent="schedule" x-on:click="chooseIntent">Send later</button><button type="submit" class="blade-primary-action" data-intent="send" x-on:click="chooseIntent" x-bind:disabled="busy"><span x-text="busy ? 'Sending…' : 'Send message'"></span></button></footer>
        </form>
    </div>
</details>
