<div class="tm-modal-scrim" x-show="createOpen" x-cloak role="presentation">
<section class="tm-modal cal-event-modal" role="dialog" aria-modal="true" aria-labelledby="calendar-create-title">
    <header class="tm-modal-head"><div class="cal-modal-title"><span><i class="fa-regular fa-calendar-plus"></i></span><h2 id="calendar-create-title">New event</h2></div><button type="button" class="tm-iconbtn" x-on:click="closeCreate" aria-label="Close event form"><i class="fa-solid fa-xmark"></i></button></header>
    @if($canCreateEvent)<form method="POST" action="{{ route('collaboration.calendar-events.store') }}" enctype="multipart/form-data">@csrf
        <input type="hidden" name="client_token" value="{{ old('client_token', (string) \Illuminate\Support\Str::uuid()) }}"><input type="hidden" name="timezone" value="{{ old('timezone',$calendarTimezone) }}">
        <div class="tm-modal-body"><div class="tm-form-grid">
            @if($companies->count()>1)<x-forms.company-context :companies="$companies" placeholder="Auto from project or attendee" />@endif
            <label class="tm-field full"><span>Event title *</span><input class="tm-input" name="title" maxlength="255" required value="{{ old('title') }}" placeholder="e.g. Site visit — Rohit Agarwal"></label>
            <label class="tm-field"><span>Event type</span><select class="tm-select" name="event_type" required>@foreach($eventTypes as $value=>$label)<option value="{{ $value }}" @selected(old('event_type','meeting')===$value)>{{ $label }}</option>@endforeach</select></label>
            <label class="tm-field"><span>Priority</span><select class="tm-select" name="metadata[priority]">@foreach(['low'=>'Low','medium'=>'Medium','high'=>'High','urgent'=>'Critical'] as $value=>$label)<option value="{{ $value }}" @selected(old('metadata.priority','medium')===$value)>{{ $label }}</option>@endforeach</select></label>
            <label class="tm-field"><span>Start *</span><input class="tm-input" type="datetime-local" name="starts_at" value="{{ old('starts_at',$focusDate->setTime(11,0)->format('Y-m-d\TH:i')) }}" required></label>
            <label class="tm-field"><span>End *</span><input class="tm-input" type="datetime-local" name="ends_at" value="{{ old('ends_at',$focusDate->setTime(12,0)->format('Y-m-d\TH:i')) }}" required></label>
            <label class="tm-field"><span>Status</span><select class="tm-select" name="status"><option value="scheduled">Scheduled</option><option value="rescheduled">Rescheduled</option></select></label>
            <label class="tm-field"><span>Project</span><select class="tm-select" name="project_id"><option value="">No project</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected(old('project_id')==$project->id)>{{ $project->code }} · {{ $project->name }}</option>@endforeach</select></label>
            <fieldset class="tm-field full people-search-picker cal-attendee-picker" x-data="peopleSearch"><legend>Assigned employees</legend><label class="tm-search people-search-input"><i class="fa-solid fa-magnifying-glass"></i><input type="search" placeholder="Search employee name, team or role..." x-on:input="filterPeople($event)" oninput="if (window.filterPeople) window.filterPeople(event);"></label><div class="people-search-results people-search-multi">@foreach($calendarUsers as $index=>$userOption)<label data-person-search="{{ strtolower($userOption->name.' '.$userOption->email.' '.($userOption->role?->name??'').' '.($userOption->employee?->department??'')) }}"><input type="checkbox" name="attendees[{{ $index }}][user_id]" value="{{ $userOption->id }}" @checked(collect(old('attendees',[]))->pluck('user_id')->contains($userOption->id))><span><b>{{ $userOption->name }}</b><small>{{ $userOption->role?->name }} · {{ $userOption->employee?->department ?? $userOption->email }}</small></span></label>@endforeach</div></fieldset>
            <label class="tm-field"><span>Location</span><input class="tm-input" name="location" maxlength="255" value="{{ old('location') }}" placeholder="Office / site address"></label>
            <label class="tm-field"><span>Online meeting link</span><input class="tm-input" type="url" name="meeting_url" maxlength="1024" value="{{ old('meeting_url') }}" placeholder="https://meet..."></label>
            <label class="tm-field"><span>Reminder</span><select class="tm-select" name="reminders[0][minutes_before]">@foreach([0=>'At event time',10=>'10 min before',15=>'15 min before',30=>'30 min before',60=>'1 hour before',1440=>'1 day before'] as $value=>$label)<option value="{{ $value }}" @selected(old('reminders.0.minutes_before',15)==$value)>{{ $label }}</option>@endforeach</select></label>
            <label class="tm-field"><span>Recurrence</span><select class="tm-select" name="recurrence[frequency]">@foreach(['none'=>'Does not repeat','daily'=>'Daily','weekly'=>'Weekly','monthly'=>'Monthly','yearly'=>'Yearly'] as $value=>$label)<option value="{{ $value }}" @selected(old('recurrence.frequency','none')===$value)>{{ $label }}</option>@endforeach</select></label>
            <label class="tm-field full"><span>Description / notes</span><textarea class="tm-textarea" name="description" maxlength="5000" placeholder="Agenda, context, talking points...">{{ old('description') }}</textarea></label>
            <details class="cal-create-advanced full"><summary>Advanced options</summary><div class="tm-form-grid">
                <label class="tm-field full"><span>External guest emails</span><textarea class="tm-textarea is-compact" name="guest_emails" placeholder="guest@company.com, another@company.com">{{ old('guest_emails') }}</textarea><small>Guests receive a secure invitation without Builder360 access.</small></label>
                <label class="tm-field"><span>Repeat interval</span><input class="tm-input" type="number" min="1" max="52" name="recurrence[interval]" value="{{ old('recurrence.interval',1) }}"></label>
                <label class="tm-field"><span>Repeat until</span><input class="tm-input" type="date" name="recurrence[until_at]" value="{{ old('recurrence.until_at') }}"></label>
                <label class="tm-field"><span>Visibility</span><select class="tm-select" name="visibility"><option value="internal" @selected(old('visibility','internal')==='internal')>Internal</option><option value="private" @selected(old('visibility')==='private')>Private</option></select></label>
                <label class="tm-field"><span>Timezone</span><input class="tm-input" value="{{ $calendarTimezone }}" disabled><small>Times are saved securely in UTC.</small></label>
                <label class="tm-field full"><span>Attachments</span><input class="tm-input" type="file" name="attachments[]" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt"></label>
            </div></details>
        </div></div>
        <footer class="tm-modal-foot"><span class="tm-modal-note"><i class="fa-solid fa-shield-halved"></i> No conflicts detected yet</span><button type="button" class="blade-secondary-action" x-on:click="closeCreate">Cancel</button><button class="blade-primary-action" type="submit"><i class="fa-solid fa-plus"></i> Create event</button></footer>
    </form>@else<div class="tm-modal-body"><p class="tm-empty-copy">Event creation is not available for this role.</p></div>@endif
</section></div>
