@php
    $eventClose=route('collaboration.calendar-events.index',$calendarQuery(['event_id'=>null]));
    $type=$eventTypeOf($selectedEvent); $color=$eventColors[$type]??'#64748b';
    $localStart=$selectedEvent->starts_at?->setTimezone($calendarTimezone); $localEnd=$selectedEvent->ends_at?->setTimezone($calendarTimezone);
    $reminder=data_get($selectedEvent->reminders,'0.minutes_before',30);
    $myAttendee=$selectedEvent->attendeeRecords->firstWhere('user_id',auth()->id());
@endphp
<div class="cal-drawer-scrim"><aside class="cal-drawer" role="dialog" aria-modal="true" aria-labelledby="calendar-drawer-title">
    <i class="cal-dr-banner" style="background:{{ $color }}"></i>
    <header class="cal-dr-head"><div class="cal-drawer-top"><span class="cal-dr-type" style="background:{{ $color }}18;color:{{ $color }}">{{ $eventTypes[$type]??str($type)->headline() }}</span><a class="tm-iconbtn" href="{{ $eventClose }}" aria-label="Close event"><i class="fa-solid fa-xmark"></i></a></div><h2 class="cal-dr-title" id="calendar-drawer-title">{{ $selectedEvent->title }}</h2><div class="cal-dr-head-meta"><span class="blade-status-pill">{{ $statuses[$selectedEvent->status]??$selectedEvent->status }}</span><span>{{ ucfirst(data_get($selectedEvent->metadata,'priority','medium')) }}</span></div></header>
    <div class="cal-dr-body">
        <div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-regular fa-clock"></i></span><span><small class="cal-dr-k">Schedule · {{ $selectedEvent->timezone }}</small><b class="cal-dr-v">{{ $localStart?->format('D, d M Y · g:i A') }} – {{ $localEnd?->format('D, d M Y · g:i A') }}</b></span></div>
        <div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-solid fa-user"></i></span><span><small class="cal-dr-k">Organizer</small><b class="cal-dr-v">{{ $selectedEvent->organizer?->name ?? 'System' }}</b></span></div>
        @if($selectedEvent->project)<div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-solid fa-building"></i></span><span><small class="cal-dr-k">Project</small><b class="cal-dr-v">{{ $selectedEvent->project->code }} · {{ $selectedEvent->project->name }}</b></span></div>@endif
        @if($selectedEvent->location)<div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-solid fa-location-dot"></i></span><span><small class="cal-dr-k">Location</small><b class="cal-dr-v">{{ $selectedEvent->location }}</b></span></div>@endif
        @if($selectedEvent->meeting_url)<div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-solid fa-video"></i></span><span><small class="cal-dr-k">Online meeting</small><a class="cal-dr-v" href="{{ $selectedEvent->meeting_url }}" target="_blank" rel="noopener noreferrer">Open secure meeting link</a></span></div>@endif
        <div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-solid fa-users"></i></span><span><small class="cal-dr-k">Attendees and responses</small><span class="cal-people">@forelse($selectedEvent->attendeeRecords as $attendee)<span class="tm-tag">{{ $attendee->name }} · {{ ucfirst($attendee->response) }}</span>@empty<span class="tm-empty-copy">No attendees</span>@endforelse</span></span></div>
        @if($myAttendee && $myAttendee->user_id !== $selectedEvent->organizer_user_id)<form class="cal-response-actions" method="POST" action="{{ route('collaboration.calendar-events.response',$selectedEvent) }}">@csrf @method('PATCH')@foreach(['accepted'=>'Accept','tentative'=>'Tentative','declined'=>'Decline'] as $value=>$label)<button class="{{ $myAttendee->response===$value?'on':'' }}" name="response" value="{{ $value }}">{{ $label }}</button>@endforeach</form>@endif
        <div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-solid fa-bell"></i></span><span><small class="cal-dr-k">Reminder and recurrence</small><b class="cal-dr-v">{{ $reminder }} minutes before · {{ ucfirst($selectedEvent->recurrenceRule?->frequency ?? 'Does not repeat') }}</b></span></div>
        @if($selectedEvent->description)<div class="cal-dr-row"><span class="cal-dr-ic"><i class="fa-regular fa-file-lines"></i></span><span><small class="cal-dr-k">Description</small><p class="cal-dr-v">{{ $selectedEvent->description }}</p></span></div>@endif

        <section class="cal-attachments"><h3>Files</h3>@forelse($selectedEvent->attachments as $attachment)<div class="cal-attachment-row"><span><i class="fa-solid fa-paperclip"></i><b>{{ $attachment->original_name }}</b><small>{{ number_format($attachment->size_bytes/1024,1) }} KB · {{ ucfirst($attachment->scan_status) }}</small></span><div>@if(str_starts_with($attachment->mime_type,'image/')||$attachment->mime_type==='application/pdf')<a href="{{ route('collaboration.calendar-events.attachments.preview',[$selectedEvent,$attachment]) }}" target="_blank" aria-label="Preview attachment"><i class="fa-regular fa-eye"></i></a>@endif<a href="{{ route('collaboration.calendar-events.attachments.download',[$selectedEvent,$attachment]) }}" aria-label="Download attachment"><i class="fa-solid fa-download"></i></a>@can('update',$selectedEvent)<form method="POST" action="{{ route('collaboration.calendar-events.attachments.destroy',[$selectedEvent,$attachment]) }}">@csrf @method('DELETE')<button aria-label="Remove attachment"><i class="fa-solid fa-trash"></i></button></form>@endcan</div></div>@empty<p class="tm-empty-copy">No files attached.</p>@endforelse
            @can('update',$selectedEvent)<form class="cal-attachment-upload" method="POST" enctype="multipart/form-data" action="{{ route('collaboration.calendar-events.attachments.store',$selectedEvent) }}">@csrf<input type="file" name="attachment" required><button class="tm-tbtn">Upload</button></form>@endcan
        </section>

        @can('update',$selectedEvent)<details class="cal-edit-details"><summary><i class="fa-solid fa-pen"></i> Edit event</summary><form method="POST" action="{{ route('collaboration.calendar-events.update',$selectedEvent) }}" class="tm-form-grid">@csrf @method('PATCH')
            <input type="hidden" name="lock_version" value="{{ $selectedEvent->lock_version }}"><input type="hidden" name="timezone" value="{{ $selectedEvent->timezone }}">
            <label class="tm-field full"><span>Title</span><input class="tm-input" name="title" value="{{ $selectedEvent->title }}" required></label><label class="tm-field"><span>Type</span><select class="tm-select" name="event_type">@foreach($eventTypes as $value=>$label)<option value="{{ $value }}" @selected($type===$value)>{{ $label }}</option>@endforeach</select></label><label class="tm-field"><span>Project</span><select class="tm-select" name="project_id"><option value="">No project</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected($selectedEvent->project_id===$project->id)>{{ $project->code }}</option>@endforeach</select></label><label class="tm-field"><span>Start</span><input class="tm-input" type="datetime-local" name="starts_at" value="{{ $localStart?->format('Y-m-d\TH:i') }}" required></label><label class="tm-field"><span>End</span><input class="tm-input" type="datetime-local" name="ends_at" value="{{ $localEnd?->format('Y-m-d\TH:i') }}" required></label><label class="tm-field"><span>Location</span><input class="tm-input" name="location" value="{{ $selectedEvent->location }}"></label><label class="tm-field"><span>Meeting URL</span><input class="tm-input" type="url" name="meeting_url" value="{{ $selectedEvent->meeting_url }}"></label><label class="tm-field"><span>Visibility</span><select class="tm-select" name="visibility"><option value="internal" @selected($selectedEvent->visibility==='internal')>Internal</option><option value="private" @selected($selectedEvent->visibility==='private')>Private</option></select></label><input type="hidden" name="metadata[priority]" value="{{ data_get($selectedEvent->metadata,'priority','medium') }}">@foreach($selectedEvent->attendeeRecords->where('attendee_type','internal') as $index=>$attendee)<input type="hidden" name="attendees[{{ $index }}][user_id]" value="{{ $attendee->user_id }}"><input type="hidden" name="attendees[{{ $index }}][response]" value="{{ $attendee->response }}">@endforeach<label class="tm-field full"><span>External guests</span><textarea class="tm-textarea is-compact" name="guest_emails">{{ $selectedEvent->attendeeRecords->where('attendee_type','guest')->pluck('email')->implode(', ') }}</textarea></label><input type="hidden" name="reminders[0][minutes_before]" value="{{ $reminder }}"><input type="hidden" name="recurrence[frequency]" value="{{ $selectedEvent->recurrenceRule?->frequency ?? 'none' }}"><label class="tm-field full"><span>Description</span><textarea class="tm-textarea" name="description">{{ $selectedEvent->description }}</textarea></label><button class="blade-primary-action" type="submit">Save changes</button>
        </form></details>@endcan
    </div>
    <footer class="cal-dr-foot">@can('complete',$selectedEvent)<form method="POST" action="{{ route('collaboration.calendar-events.complete',$selectedEvent) }}">@csrf @method('PATCH')<input type="hidden" name="lock_version" value="{{ $selectedEvent->lock_version }}"><input type="hidden" name="note" value="Completed from Calendar Management"><button class="blade-primary-action" type="submit"><i class="fa-solid fa-check"></i> Complete</button></form>@endcan @can('cancel',$selectedEvent)<details><summary class="blade-secondary-action">Cancel</summary><form method="POST" action="{{ route('collaboration.calendar-events.cancel',$selectedEvent) }}">@csrf @method('PATCH')<input type="hidden" name="lock_version" value="{{ $selectedEvent->lock_version }}"><input class="tm-input" name="reason" required placeholder="Cancellation reason"><button class="blade-danger-action" type="submit">Confirm cancel</button></form></details>@endcan @can('delete',$selectedEvent)<form method="POST" action="{{ route('collaboration.calendar-events.destroy',$selectedEvent) }}">@csrf @method('DELETE')<input type="hidden" name="lock_version" value="{{ $selectedEvent->lock_version }}"><input type="hidden" name="reason" value="Archived from Calendar Management"><button class="blade-danger-action" type="submit"><i class="fa-solid fa-box-archive"></i> Archive</button></form>@endcan</footer>
</aside></div>
