<?php
namespace App\Http\Controllers\Maintenance;
use App\Application\Maintenance\Actions\CreateSocietyFormation; use App\Application\Maintenance\Actions\ListCommonAreaHandoverWorkspace; use App\Application\Maintenance\Actions\ListMaintenanceDueWorkspace; use App\Application\Maintenance\Actions\ListSocietyWorkspace; use App\Application\Maintenance\Actions\MarkMaintenanceDuePaid; use App\Application\Maintenance\Actions\RaiseMaintenanceDue; use App\Application\Maintenance\Actions\RemindMaintenanceDue; use App\Application\Maintenance\Actions\SignOffCommonAreaHandover; use App\Application\Maintenance\Actions\UpdateCommonAreaHandover; use App\Application\Maintenance\Actions\UpdateSocietyFormationStatus; use App\Application\Maintenance\Data\MaintenanceCommandData;
use App\Http\Controllers\Controller; use App\Http\Requests\Maintenance\CommonAreaHandoverItemIndexRequest; use App\Http\Requests\Maintenance\MaintenanceDueIndexRequest; use App\Http\Requests\Maintenance\MarkMaintenanceDuePaidRequest; use App\Http\Requests\Maintenance\RemindMaintenanceDueRequest; use App\Http\Requests\Maintenance\SignOffCommonAreaHandoverItemRequest; use App\Http\Requests\Maintenance\SocietyFormationIndexRequest; use App\Http\Requests\Maintenance\StoreMaintenanceDueRequest; use App\Http\Requests\Maintenance\StoreSocietyFormationRequest; use App\Http\Requests\Maintenance\UpdateCommonAreaHandoverItemRequest; use App\Http\Requests\Maintenance\UpdateSocietyFormationStatusRequest; use App\Http\Resources\CommonAreaHandoverItemResource; use App\Http\Resources\MaintenanceDueResource; use App\Http\Resources\SocietyFormationResource; use App\Models\CommonAreaHandoverItem; use App\Models\MaintenanceDue; use App\Models\SocietyFormation; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Resources\Json\AnonymousResourceCollection; use Illuminate\View\View;
class MaintenanceSocietyController extends Controller
{
    public function societies(SocietyFormationIndexRequest $request,ListSocietyWorkspace $list): AnonymousResourceCollection|View { $w=$list->execute($request->user(),$request->validated()); return $request->wantsJson()?SocietyFormationResource::collection($w->societies):view('maintenance.societies.index',$w->toView()); }
    public function storeSociety(StoreSocietyFormationRequest $request,CreateSocietyFormation $create): SocietyFormationResource|RedirectResponse { $m=$create->execute(new MaintenanceCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new SocietyFormationResource($m))->additional(['message'=>'Society formation created.']):redirect()->route('maintenance.societies.index')->with('status',"Society formation {$m->formation_number} created."); }
    public function updateSocietyStatus(SocietyFormation $societyFormation,UpdateSocietyFormationStatusRequest $request,UpdateSocietyFormationStatus $update): SocietyFormationResource|RedirectResponse { $m=$update->execute($societyFormation,new MaintenanceCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new SocietyFormationResource($m))->additional(['message'=>'Society formation updated.']):redirect()->route('maintenance.societies.index')->with('status',"Society formation {$m->formation_number} updated."); }
    public function handoverItems(CommonAreaHandoverItemIndexRequest $request,ListCommonAreaHandoverWorkspace $list): AnonymousResourceCollection|View { $w=$list->execute($request->user(),$request->validated()); return $request->wantsJson()?CommonAreaHandoverItemResource::collection($w->items):view('maintenance.handover-items.index',$w->toView()); }
    public function updateHandoverItem(CommonAreaHandoverItem $commonAreaHandoverItem,UpdateCommonAreaHandoverItemRequest $request,UpdateCommonAreaHandover $update): CommonAreaHandoverItemResource|RedirectResponse { $m=$update->execute($commonAreaHandoverItem,new MaintenanceCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new CommonAreaHandoverItemResource($m))->additional(['message'=>'Common-area handover checklist updated.']):redirect()->route('maintenance.handover-items.index')->with('status',"Common-area handover item {$m->item_number} updated."); }
    public function signOffHandoverItem(CommonAreaHandoverItem $commonAreaHandoverItem,SignOffCommonAreaHandoverItemRequest $request,SignOffCommonAreaHandover $signOff): CommonAreaHandoverItemResource|RedirectResponse { $m=$signOff->execute($commonAreaHandoverItem,new MaintenanceCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new CommonAreaHandoverItemResource($m))->additional(['message'=>'Common-area handover item signed off.']):redirect()->route('maintenance.handover-items.index')->with('status',"Common-area handover item {$m->item_number} signed off."); }
    public function dues(MaintenanceDueIndexRequest $request,ListMaintenanceDueWorkspace $list): AnonymousResourceCollection|View { $w=$list->execute($request->user(),$request->validated()); return $request->wantsJson()?MaintenanceDueResource::collection($w->dues):view('maintenance.dues.index',$w->toView()); }
    public function storeDue(StoreMaintenanceDueRequest $request,RaiseMaintenanceDue $raise): MaintenanceDueResource|RedirectResponse { $m=$raise->execute(new MaintenanceCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new MaintenanceDueResource($m))->additional(['message'=>'Maintenance due raised.']):redirect()->route('maintenance.dues.index')->with('status',"Maintenance due {$m->due_number} raised."); }
    public function markDuePaid(MaintenanceDue $maintenanceDue,MarkMaintenanceDuePaidRequest $request,MarkMaintenanceDuePaid $mark): MaintenanceDueResource|RedirectResponse { $m=$mark->execute($maintenanceDue,new MaintenanceCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new MaintenanceDueResource($m))->additional(['message'=>'Maintenance payment recorded.']):redirect()->route('maintenance.dues.index')->with('status',"Maintenance payment recorded for {$m->due_number}."); }
    public function remindDue(MaintenanceDue $maintenanceDue,RemindMaintenanceDueRequest $request,RemindMaintenanceDue $remind): MaintenanceDueResource|RedirectResponse { $m=$remind->execute($maintenanceDue,new MaintenanceCommandData($request->validated(),$request->user(),$request)); return $request->wantsJson()?(new MaintenanceDueResource($m))->additional(['message'=>'Maintenance reminder recorded.']):redirect()->route('maintenance.dues.index')->with('status',"Maintenance reminder recorded for {$m->due_number}."); }
}
