@extends('layouts.builder360-classic')
@section('title', 'My Payments - Builder360 ERP-CRM')
@section('content')
<div class="blade-workspace" aria-labelledby="buyer-payments-title">
<header class="blade-workspace-header"><div><p class="blade-dashboard-eyebrow">Buyer Portal</p><h1 id="buyer-payments-title">My Payments</h1><p>Payment requests and their current completion status.</p></div>@include('buyer.partials.navigation')</header>
@if(session('status'))<div class="blade-alert blade-alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="blade-alert blade-alert-danger"><strong>Check the payment details.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="blade-dashboard-card"><form method="GET" action="{{ route('buyer.payment-requests.index') }}" class="blade-filter-grid blade-filter-grid-compact"><label>Status<select name="status"><option value="">All statuses</option>@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected(($filters['status']??'')===$value)>{{ $label }}</option>@endforeach</select></label><button class="blade-secondary-action">Apply filter</button><a class="blade-secondary-action" href="{{ route('buyer.payment-requests.index') }}">Reset</a></form></section>
<section class="blade-dashboard-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Payments</span><h2>Payment request register</h2></div><small>{{ $records->total() }} record(s)</small></div><div class="blade-dashboard-table-wrap"><table class="blade-dashboard-table"><thead><tr><th>Request</th><th>Booking</th><th>Purpose</th><th>Amount</th><th>Expires</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($records as $payment)<tr><td><strong>{{ $payment->request_number }}</strong></td><td>{{ $payment->booking?->booking_code ?? '—' }}</td><td>{{ $payment->purpose }}</td><td>₹{{ number_format((float)$payment->amount,2) }}</td><td>{{ $payment->expires_at?->format('d M Y') ?? '—' }}</td><td><span class="blade-status-pill">{{ $statuses[$payment->status] ?? ucfirst($payment->status) }}</span></td><td>@if($payment->status==='requested')<details class="blade-row-actions"><summary>Pay</summary><form method="POST" action="{{ route('buyer.payment-requests.pay',$payment) }}" class="blade-inline-form">@csrf @method('PATCH')<select name="payment_mode" required><option value="upi">UPI</option><option value="card">Card</option><option value="netbanking">Net Banking</option><option value="wallet">Wallet</option></select><input name="instrument_number" placeholder="Transaction reference" required maxlength="120"><button class="blade-primary-action" type="submit">Complete payment</button></form></details>@else<span class="blade-muted">No action</span>@endif</td></tr>@empty<tr><td colspan="7">No payment requests are available.</td></tr>@endforelse
</tbody></table></div><div class="blade-pagination">{{ $records->links() }}</div></section></div>
@endsection
