@extends('layouts.builder360-classic')
@section('title', 'My Service Tickets - Builder360 ERP-CRM')
@section('content')
<div class="blade-workspace" aria-labelledby="buyer-tickets-title"><header class="blade-workspace-header"><div><p class="blade-dashboard-eyebrow">Buyer Portal</p><h1 id="buyer-tickets-title">My Service Tickets</h1><p>Track requests, response targets, resolution and closure.</p></div>@include('buyer.partials.navigation')</header>
@if(session('status'))<div class="blade-alert blade-alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="blade-alert blade-alert-danger"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="blade-workspace-grid"><article class="blade-dashboard-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Create</span><h2>Raise service ticket</h2></div></div>@if($customer)<form method="POST" action="{{ route('buyer.service-tickets.store') }}" class="blade-form-grid">@csrf<label>Booking<select name="booking_id" required>@foreach($customer->bookings()->whereIn('status',['confirmed','agreement_pending','registered'])->orderBy('booking_code')->get() as $booking)<option value="{{ $booking->id }}">{{ $booking->booking_code }}</option>@endforeach</select></label><label>Category<select name="category" required>@foreach($categories as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label>Priority<select name="priority" required>@foreach($priorities as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="blade-form-wide">Subject<input name="subject" required maxlength="180"></label><label class="blade-form-wide">Description<textarea name="description" required maxlength="3000"></textarea></label><button class="blade-primary-action" type="submit">Raise ticket</button></form>@else<p class="blade-muted">A linked customer profile is required.</p>@endif</article>
<article class="blade-dashboard-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Filters</span><h2>Find tickets</h2></div></div><form method="GET" action="{{ route('buyer.service-tickets.index') }}" class="blade-form-grid"><label>Status<select name="status"><option value="">All</option>@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected(($filters['status']??'')===$value)>{{ $label }}</option>@endforeach</select></label><label>Category<select name="category"><option value="">All</option>@foreach($categories as $value=>$label)<option value="{{ $value }}" @selected(($filters['category']??'')===$value)>{{ $label }}</option>@endforeach</select></label><label>Priority<select name="priority"><option value="">All</option>@foreach($priorities as $value=>$label)<option value="{{ $value }}" @selected(($filters['priority']??'')===$value)>{{ $label }}</option>@endforeach</select></label><button class="blade-secondary-action">Apply filters</button></form></article></section>
<section class="blade-dashboard-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Tickets</span><h2>Service ticket register</h2></div><small>{{ $records->total() }} record(s)</small></div><div class="blade-dashboard-table-wrap"><table class="blade-dashboard-table"><thead><tr><th>Ticket</th><th>Booking</th><th>Priority</th><th>SLA</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($records as $ticket)<tr><td><strong>{{ $ticket->ticket_number }}</strong><span>{{ $ticket->subject }}</span></td><td>{{ $ticket->booking?->booking_code ?? '—' }}</td><td>{{ $priorities[$ticket->priority] ?? ucfirst($ticket->priority) }}</td><td>{{ $ticket->sla_due_at?->format('d M Y H:i') ?? '—' }}</td><td><span class="blade-status-pill">{{ $statuses[$ticket->status] ?? ucfirst($ticket->status) }}</span></td><td>@if($ticket->status==='resolved')<form method="POST" action="{{ route('buyer.service-tickets.close',$ticket) }}" class="blade-inline-form">@csrf @method('PATCH')<input type="number" name="customer_rating" min="1" max="5" required placeholder="Rating 1–5"><input name="note" maxlength="1000" placeholder="Closure note"><button class="blade-primary-action">Close ticket</button></form>@else<span class="blade-muted">No action</span>@endif</td></tr>@empty<tr><td colspan="6">No service tickets are available.</td></tr>@endforelse</tbody></table></div><div class="blade-pagination">{{ $records->links() }}</div></section></div>
@endsection
