<section class="people-ops-stack" data-recruitment-surface="interviews">
    @if($abilities['canScheduleInterview'])
        <details id="recruitment-create" class="people-ops-panel" @if($errors->any()) open @endif><summary class="people-ops-panel-head"><div><h2>Schedule interview</h2><p>Panel availability and company scope are revalidated by the server.</p></div><span class="people-button"><i class="fa-solid fa-plus" aria-hidden="true"></i> Interview</span></summary>
            <form method="POST" action="{{ route('recruitment.interviews.store') }}" class="people-form-grid people-ops-panel-body">@csrf
                <label class="people-field">Candidate<select name="candidate_id" required><option value="">Select candidate</option>@foreach($activeCandidateOptions as $candidate)<option value="{{ $candidate->id }}" @selected((string)old('candidate_id') === (string)$candidate->id)>{{ $candidate->candidate_code }} · {{ $candidate->name }}</option>@endforeach</select></label>
                <label class="people-field">Round<input name="round_name" value="{{ old('round_name', 'Technical Round') }}" maxlength="120" required></label>
                <label class="people-field">Scheduled at<input type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at') }}" required></label>
                <label class="people-field">Duration minutes<input type="number" name="duration_minutes" value="{{ old('duration_minutes', 60) }}" min="15" max="480" required></label>
                <label class="people-field">Mode<select name="mode" required>@foreach($interviewModes as $value => $label)<option value="{{ $value }}" @selected(old('mode', 'video') === $value)>{{ $label }}</option>@endforeach</select></label>
                <label class="people-field">Venue or meeting link<input name="venue_or_link" value="{{ old('venue_or_link') }}" maxlength="500"></label>
                <label class="people-field is-wide">Panel members<select name="panel_user_ids[]" multiple required>@foreach($panelUsers as $member)<option value="{{ $member->id }}" @selected(in_array((string)$member->id, array_map('strval', old('panel_user_ids', [])), true))>{{ $member->name }} · {{ $member->email }}</option>@endforeach</select><small>Select one or more active internal users in the candidate company.</small></label>
                <div class="people-field is-wide"><button class="people-button is-primary" type="submit">Schedule interview</button></div>
            </form>
        </details>
    @endif

    <form method="GET" action="{{ route('recruitment.interviews.index') }}" class="people-ops-filterbar"><label class="people-field">Status<select name="status"><option value="">All statuses</option>@foreach($interviewStatuses as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></label><label class="people-field">Interview date<input type="date" name="date" value="{{ $filters['date'] ?? '' }}"></label><button class="people-button" type="submit"><i class="fa-solid fa-filter" aria-hidden="true"></i> Apply</button>@if(array_filter($filters))<a class="people-button" href="{{ route('recruitment.interviews.index') }}">Clear</a>@endif</form>

    <article class="people-ops-panel has-mobile-cards"><header class="people-ops-panel-head"><div><h2>Interview schedule</h2><p>Only assigned panel members may submit feedback.</p></div><small>{{ $interviews->firstItem() ?? 0 }}–{{ $interviews->lastItem() ?? 0 }} of {{ $interviews->total() }}</small></header>
        <div class="people-ops-table-wrap"><table class="people-ops-table"><caption>Scheduled recruitment interviews</caption><thead><tr><th scope="col">Interview</th><th scope="col">Candidate</th><th scope="col">Schedule</th><th scope="col">Panel</th><th scope="col">Status</th><th scope="col">Score</th><th scope="col">Feedback</th></tr></thead><tbody>
        @forelse($interviews as $interview)<tr><td><strong>{{ $interview->code }}</strong><small>{{ $interview->round }} · {{ $interview->mode }}</small></td><td>{{ $interview->candidateName }}<small>{{ $interview->candidateCode }} · {{ $interview->openingTitle }}</small></td><td>{{ $interview->scheduledDate }}<small>{{ $interview->scheduledTime }} · {{ $interview->duration }}</small></td><td>{{ implode(', ', $interview->panel) ?: 'No panel' }}<small>{{ $interview->submittedFeedback }}/{{ $interview->expectedFeedback }} feedback received</small></td><td><span class="people-status {{ $interview->statusTone }}">{{ $interview->statusLabel }}</span></td><td>@if($interview->score)<strong>{{ $interview->score }} / 100</strong><small>{{ $interview->scoreBand }} · {{ $interview->scoreRule }}</small>@elseif($interview->averageRating)<strong>{{ $interview->averageRating }}</strong><small>Panel average</small>@else<span class="people-status is-muted">Not calculated</span>@endif</td><td class="is-actions">
            @if($interview->canSubmitFeedback)<details><summary class="people-ops-action-link">Add feedback</summary><form method="POST" action="{{ route('recruitment.interviews.feedback', $interview->id) }}" class="people-ops-stack">@csrf @method('PATCH')<label class="people-field">Rating<input type="number" name="rating" min="1" max="5" value="4" required></label><label class="people-field">Recommendation<select name="recommendation" required><option value="selected">Selected</option><option value="second_round">Second round</option><option value="hold">Hold</option><option value="rejected">Rejected</option></select></label><label class="people-field">Feedback<input name="feedback_note" maxlength="3000"></label><button class="people-button is-primary" type="submit">Submit</button></form></details>@else<span class="people-status is-muted">Unavailable</span>@endif
        </td></tr>@empty<tr><td colspan="7"><div class="people-ops-empty"><i class="fa-regular fa-calendar-check" aria-hidden="true"></i><strong>No interviews found</strong><span>Change the filters or schedule an authorized candidate interview.</span></div></td></tr>@endforelse
        </tbody></table></div>
        <div class="people-ops-mobile-list">
            @forelse($interviews as $interview)
                <article class="people-ops-mobile-card">
                    <header class="people-ops-mobile-card-head"><div><strong>{{ $interview->candidateName }}</strong><small>{{ $interview->code }} · {{ $interview->round }}</small></div><span class="people-status {{ $interview->statusTone }}">{{ $interview->statusLabel }}</span></header>
                    <dl class="people-ops-mobile-facts"><div><dt>Date</dt><dd>{{ $interview->scheduledDate }} {{ $interview->scheduledTime }}</dd></div><div><dt>Mode</dt><dd>{{ $interview->mode }}</dd></div><div><dt>Panel</dt><dd>{{ implode(', ', $interview->panel) ?: 'No panel' }}</dd></div><div><dt>Feedback</dt><dd>{{ $interview->submittedFeedback }}/{{ $interview->expectedFeedback }}</dd></div></dl>
                    @if($interview->canSubmitFeedback)
                        <div class="people-ops-mobile-actions"><details><summary class="people-button">Add feedback</summary><form method="POST" action="{{ route('recruitment.interviews.feedback', $interview->id) }}" class="people-ops-stack">@csrf @method('PATCH')<label class="people-field">Rating<input type="number" name="rating" min="1" max="5" value="4" required></label><label class="people-field">Recommendation<select name="recommendation" required><option value="selected">Selected</option><option value="second_round">Second round</option><option value="hold">Hold</option><option value="rejected">Rejected</option></select></label><label class="people-field">Feedback<input name="feedback_note" maxlength="3000"></label><button class="people-button is-primary" type="submit">Submit feedback</button></form></details></div>
                    @endif
                </article>
            @empty
                <div class="people-ops-empty"><strong>No interviews found</strong><span>Change the filters or schedule an authorized candidate interview.</span></div>
            @endforelse
        </div>
        <div class="people-pagination">{{ $interviews->links() }}</div>
    </article>
</section>
