<section class="people-ops-grid is-wide-left" aria-label="Leave encashment operations">
    <article class="people-ops-panel">
        <header class="people-ops-panel-head"><div><h2>Request leave encashment</h2><p>Submit eligible leave days for policy validation and approval.</p></div></header>
        <div class="people-ops-panel-body">
            @if($abilities['canCreateEncashment'])
                <form method="POST" action="{{ route('hr.leave-encashments.store') }}" class="people-form-grid">@csrf
                    <label class="people-field"><span>Employee</span><select class="people-control" name="employee_id" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((string)old('employee_id')===(string)$employee->id)>{{ $employee->employee_code }} - {{ $employee->name }}</option>@endforeach</select>@error('employee_id')<small class="people-field-error">{{ $message }}</small>@enderror</label>
                    <label class="people-field"><span>Leave type</span><select class="people-control" name="leave_type_id" required><option value="">Select eligible leave type</option>@foreach($leaveTypeOptions as $type)<option value="{{ $type->id }}" @selected((string)old('leave_type_id')===(string)$type->id)>{{ $type->code }} - {{ $type->name }}</option>@endforeach</select>@error('leave_type_id')<small class="people-field-error">{{ $message }}</small>@enderror</label>
                    <label class="people-field"><span>Period year</span><input class="people-control" type="number" name="period_year" min="2000" max="2100" value="{{ old('period_year', now()->year) }}" required>@error('period_year')<small class="people-field-error">{{ $message }}</small>@enderror</label>
                    <label class="people-field"><span>Requested days</span><input class="people-control" type="number" name="requested_days" min="0.5" max="365" step="0.5" value="{{ old('requested_days') }}" required>@error('requested_days')<small class="people-field-error">{{ $message }}</small>@enderror</label>
                    <label class="people-field is-wide"><span>Request note</span><textarea class="people-control" name="request_note" maxlength="1000" rows="3">{{ old('request_note') }}</textarea>@error('request_note')<small class="people-field-error">{{ $message }}</small>@enderror</label>
                    <div class="people-modal-actions is-wide"><button class="people-button is-primary" type="submit">Submit encashment</button></div>
                </form>
            @else<div class="people-ops-empty"><i class="fa-solid fa-lock" aria-hidden="true"></i><strong>Encashment unavailable</strong><span>Your role cannot submit leave encashment requests.</span></div>@endif
        </div>
    </article>
    <article class="people-ops-panel"><header class="people-ops-panel-head"><div><h2>Encashment workflow</h2><p>Calculation and posting remain server-authoritative.</p></div></header><ul class="people-ops-checklist"><li><i class="fa-solid fa-check" aria-hidden="true"></i><span>Eligibility and available balance validated</span><strong>On submit</strong></li><li><i class="fa-solid fa-check" aria-hidden="true"></i><span>Approval adjusts the leave ledger once</span><strong>Audited</strong></li><li><i class="fa-solid fa-check" aria-hidden="true"></i><span>Payroll handoff requires payroll permission</span><strong>Separated</strong></li></ul></article>
</section>

<section class="people-ops-panel" aria-labelledby="leave-encashments-title"><header class="people-ops-panel-head"><div><h2 id="leave-encashments-title">Leave encashments</h2><p>Request, approval, and payroll handoff states.</p></div></header>
    <div class="people-ops-panel-body"><form method="GET" action="{{ route('hr.leave-encashments.index') }}" class="people-ops-filterbar"><label class="people-field"><span>Employee</span><select class="people-control" name="employee_id"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((string)request('employee_id')===(string)$employee->id)>{{ $employee->employee_code }} - {{ $employee->name }}</option>@endforeach</select></label><label class="people-field"><span>Year</span><input class="people-control" type="number" name="period_year" min="2000" max="2100" value="{{ request('period_year') }}"></label><label class="people-field"><span>Status</span><select class="people-control" name="status"><option value="">All statuses</option>@foreach($encashmentStatuses as $status)<option value="{{ $status['value'] }}" @selected(request('status')===$status['value'])>{{ $status['label'] }}</option>@endforeach</select></label><button class="people-button" type="submit">Apply filters</button><a class="people-button" href="{{ route('hr.leave-encashments.index') }}">Clear</a></form></div>
    <div class="people-ops-table-wrap"><table class="people-ops-table"><caption>Leave encashment register</caption><thead><tr><th scope="col">Encashment</th><th scope="col">Employee</th><th scope="col">Leave / year</th><th scope="col">Days</th><th scope="col">Amount</th><th scope="col">Status</th><th scope="col">Notes</th><th scope="col" class="is-actions">Action</th></tr></thead><tbody>
        @forelse($encashments as $item)<tr><td><strong>{{ $item->encashmentNumber }}</strong></td><td><div class="people-ops-identity"><div><strong>{{ $item->employeeName }}</strong><small>{{ $item->employeeCode }}</small></div></div></td><td>{{ $item->leaveTypeCode }}<small>{{ $item->periodYear }}</small></td><td>Requested {{ $item->requestedDays }}<small>Approved {{ $item->approvedDays }}</small></td><td>{{ $item->grossAmount }}<small>Net {{ $item->netAmount }}</small></td><td><span class="people-status is-{{ $item->status }}">{{ $item->statusLabel }}</span></td><td>{{ $item->requestNote }}@if($item->decisionNote)<small>Decision: {{ $item->decisionNote }}</small>@endif @if($item->payrollReference)<small>Payroll: {{ $item->payrollReference }}</small>@endif</td><td class="is-actions">
            @if($item->canApprove)<form method="POST" action="{{ route('hr.leave-encashments.approve', $item->id) }}">@csrf @method('PATCH')<input class="people-control" type="number" name="approved_days" min="0.5" max="365" step="0.5" placeholder="Approved days"><input class="people-control" name="decision_note" maxlength="1000" placeholder="Approval note"><button class="people-ops-action-link" type="submit">Approve</button></form>@endif
            @if($item->canReject)<form method="POST" action="{{ route('hr.leave-encashments.reject', $item->id) }}">@csrf @method('PATCH')<input class="people-control" name="decision_note" maxlength="1000" placeholder="Rejection reason" required><button class="people-ops-action-link is-danger" type="submit">Reject</button></form>@endif
            @if($item->canMarkPayroll)<form method="POST" action="{{ route('hr.leave-encashments.mark-payroll', $item->id) }}">@csrf @method('PATCH')<input class="people-control" name="payroll_reference" maxlength="120" placeholder="Payroll reference" required><input class="people-control" name="note" maxlength="1000" placeholder="Payroll note"><button class="people-ops-action-link" type="submit">Mark payroll</button></form>@endif
            @if(! $item->canApprove && ! $item->canReject && ! $item->canMarkPayroll)<span class="people-subtext">No action</span>@endif
        </td></tr>@empty<tr><td colspan="8"><div class="people-ops-empty"><strong>No leave encashments found</strong><span>No requests match the selected filters.</span></div></td></tr>@endforelse
    </tbody></table></div><div class="people-pagination">{{ $encashments->withQueryString()->links() }}</div>
</section>
